### ISSUE TITLE
Implement `ltsp isc-dhcp`

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#10]
`ltsp dnsmasq` generates an appropriate /etc/ltsp/ltsp-dnsmasq.conf configuration file for TFTP and optionally DHCP, proxyDHCP and DNS services that the clients may need to netboot.

To chose tftpd-hpa for TFTP services instead, one could just run `ltsp dnsmasq --tftp=0; apt install tftpd-hpa`; no additional configuration is needed.

But to choose isc-dhcp-server for DHCP services, it would be nice to implement an `ltsp isc-dhcp` command, that would create an appropriate dhcpd.conf configuration file, that works for BIOS, UEFI and iPXE clients like ltsp-dnsmasq.conf.

If someone does need this and is able to test things, please reply to this issue.

**Comment by alkisg** [comment]
The syntax for isc-dhcp is mentioned [there](https://wiki.syslinux.org/wiki/index.php?title=PXELINUX#UEFI).

**Comment by alkisg** [comment]
Taking into account that:

- Only dnsmasq can support proxyDHCP, so we recommend it over isc-dhcp-server
- Dnsmasq works out of the box in dual NIC setups too
- Sysadmins may be running isc-dhcp-server externally, not on the LTSP server
- In that case, proxyDHCP on dnsmasq is again easier to setup

...I decided not to implement `ltsp isc-dhcp`, but to provide a wiki page with a template dhcpd.conf and instructions instead:
https://github.com/ltsp/ltsp/wiki/isc-dhcp-server

**Comment by trickkiste** [comment]
Hi Alkisg,

for the CephFS/RBD LTSP setup I am currently working on, it would be beneficial to have an isc-dhcp-server option available. I am using MAAS to orchestrate my Ceph cluster, and MAAS also provides a isc-dhcp-server instance. For this setup a snippet with the LTSP specific options is needed, which then can then be added to a MAAS managed subnet.

Thank you for putting up the Wiki page for this topic, I can manage with the information there, but I thought I give you a few details on my specific use case as an example of an alternative deployment.

My best regards,
Markus

**Comment by alkisg** [comment]
trickkiste, configuring isc-dhcp involves just one file; it's just for dhcp, it doesn't have all the tftp/dns options that dnsmasq has.

What more would an`ltsp isc-dhcp-server` offer, that the example file doesn't include?
