### ISSUE TITLE
Feature request: On server shutdown, halt the server shutdown and get epoptes to shutdown the clients.

### ISSUE THREAD

**Issue by Rillian-Grant** [ltsp/ltsp#101]

**Comment by alkisg** [comment]
Hi Rillian-Grant,

sorry but currently Epoptes isn't scriptable so it's impossible to implement this feature that way.

You might be able to block shutdown for e.g. two minutes with a systemd unit, and have it create a shutting-down file in NFS, and have the clients poll for the existence of that file every minute.
