### ISSUE TITLE
var/spool/squid/* should be added to image.excludes 

### ISSUE THREAD

**Issue by schweer-guest** [ltsp/ltsp#106]
Since some time, Squid (in Debian) switched back to /var/spool/squid.
This change occurred in the Stretch release.
So maybe both var/spool/squid3/* and var/spool/squid/* should be listed.

Wolfgang

**Comment by alkisg** [comment]
Thanks, fix committed in b63fa5f9789646519cc2d00fea36ff323a6faf27.
