### ISSUE TITLE
Wrong tftp-root in ltsp-dnsmasq.conf template

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#107]
ltsp-dnsmasq.conf contains:

```shell
# FHS 2.3+ recommends /srv for tftp (debian #477109, LP #84615)
tftp-root=/srv/ltsp
```

That should be /srv/tftp there. The generated file is  fine though, the problem is only in the template.

**Comment by alkisg** [comment]
Thanks, fix committed in 36d0f7478a4ccb2ce35d1caaa8b0114b8bb0eac7.
