### ISSUE TITLE
ltsp initrd throws error when host does not contain ssh keys

### ISSUE THREAD

**Issue by kvaps** [ltsp/ltsp#111]
```bash
# ltsp initrd
sed: can't read /etc/ssh/ssh_host_*_key.pub: No such file or directory
LTSP command failed: sed s/^/server / /etc/ssh/ssh_host_*_key.pub
Generated ltsp.img:
-rw-r--r-- 1 root root 148100 Dec 19 16:47 /srv/tftp/ltsp/ltsp.img
```

I assume something messy up with `$_DST_DIR` here, and we need to check `/etc/ssh/ssh_host_*_key.pub` existence:

https://github.com/ltsp/ltsp/blob/4734f8077eec9f71c96ce6a50c7e8d4fec0d3e86/ltsp/common/initrd/35-initrd.sh#L40-L46

**Comment by alkisg** [comment]
For pamltsp and sshfs to work, the public server keys are required in ltsp.img.
If a different server is to be used instead, the administrator can provide its keys in /etc/ltsp/ssh_known_hosts.

Both of these are fine; but for the case where SSH/SSHFS is *not* used, there needs to be an additional check "if $NO_SSH ... then don't bother".

**Comment by kvaps** [comment]
But command finishes with 0 exit-code anyway.
Wouldn't be more clean for add reliable warning in this place, eg:
```bash
warn "ssh host keys not found, pamltsp and sshfs won't work"
```

**Comment by alkisg** [comment]
The re and rw function calls and respective error messages are good when we don't expect that error to happen often.
If some error happens often, then we can replace the rw or re call with an "if ! cmd; then warn "error message"; fi".
On the other hand, if we do that for all re or rw calls, then the code will no longer be readable, it'll be full of error messages.

So the question is, how often does this issue happen... the default ltsp installation states `apt install ltsp ... openssh-server`, so shouldn't we expect to have sshd installed?
