### ISSUE TITLE
Cannot create ltsp image from VM

### ISSUE THREAD

**Issue by mhwasil** [ltsp/ltsp#112]
I tried to create ltsp image using virtual box image (with vmdk and fixec size disk).
The image runs well on virtual box.
I tried the following command to create symlink to the image as mentioned in [the documentation](https://ltsp.org/man/ltsp-image/)
```
ln -rs /home/admin/VirtualBoxVMs/debian/debian10-flat.vmdk /srv/ltsp/debian.img
```
and generated ltsp image by:
```
ltsp image debian
```
but it gave me the following error
```
root@server:/srv/ltsp# ltsp image debian
Running:  losetup /dev/loop0 /srv/ltsp/debian.img
blkid: error: /dev/loop0p*: No such file or directory
LTSP command failed: blkid -po export /dev/loop0p*
Aborting ltsp
I don't know how to mount /srv/ltsp/debian.img
```

**Comment by alkisg** [comment]
Hi, what's the output of these commands?

```shell
su -
grep PRETTY /etc/os-release
blkid /srv/ltsp/debian.img
fdisk -l /srv/ltsp/debian.img
losetup /dev/loop1 /srv/ltsp/debian.img
blkid /dev/loop1
losetup -d /dev/loop1
losetup -rP /dev/loop1 /srv/ltsp/debian.img
blkid /dev/loop1
losetup -d /dev/loop1
```

**Comment by mhwasil** [comment]
Thank you for your quick response,
Here are the outputs:
```
root@server:~# grep PRETTY /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
root@server:~# blkid /srv/ltsp/debian.img
/srv/ltsp/debian.img: PTUUID="c4bd335b" PTTYPE="dos"
root@server:~# fdisk -l /srv/ltsp/debian.img
Disk /srv/ltsp/debian.img: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc4bd335b

Device                Boot    Start      End  Sectors Size Id Type
/srv/ltsp/debian.img1 *        2048 37748735 37746688  18G 83 Linux
/srv/ltsp/debian.img2      37750782 41940991  4190210   2G  5 Extended
/srv/ltsp/debian.img5      37750784 41940991  4190208   2G 82 Linux swap / Solaris
root@server:~# losetup /dev/loop1 /srv/ltsp/debian.img
root@server:~# blkid /dev/loop1
/dev/loop1: PTUUID="c4bd335b" PTTYPE="dos"
root@server:~# losetup -d /dev/loop1
root@server:~# losetup -rP /dev/loop1 /srv/ltsp/debian.img
root@server:~# blkid /dev/loop1
/dev/loop1: PTUUID="c4bd335b" PTTYPE="dos"
root@server:~# losetup -d /dev/loop1
root@server:~# 
```

**Comment by alkisg** [comment]
That's strange... before testing more commands, could you please try the latest LTSP from the [proposed PPA](https://ltsp.org/advanced/proposed-ppa/)? It has some changes in that specific part of the codebase.

**Comment by alkisg** [comment]
To have more info sooner, if the newest LTSP doesn't work, also mention the output of these:

```shell
losetup /dev/loop2 /srv/ltsp/debian.img
echo /dev/loop2*
losetup -d /dev/loop2
losetup -rP /dev/loop2 /srv/ltsp/debian.img
echo /dev/loop2*
losetup -d /dev/loop2
```

**Comment by mhwasil** [comment]
I tried the new PPA and reinstall ltsp, but I still got the same error.
and the output
```
root@server:~# losetup /dev/loop2 /srv/ltsp/debian.img
root@server:~# echo /dev/loop2*
/dev/loop2 /dev/loop2p1 /dev/loop2p2 /dev/loop2p5
root@server:~# losetup -d /dev/loop2
root@server:~# losetup -rP /dev/loop2 /srv/ltsp/debian.img
root@server:~# echo /dev/loop2*
/dev/loop2 /dev/loop2p1 /dev/loop2p2 /dev/loop2p5
root@server:~# losetup -d /dev/loop2
root@server:~# 

```

**Comment by alkisg** [comment]
Strange; how easy would it be for you to come over to [IRC](ts.sch.gr/repo/irc/) for live remote support?

**Comment by alkisg** [comment]
We basically want to put a `debug_shell` call in https://github.com/ltsp/ltsp/blob/master/ltsp/common/ltsp/55-images.sh#L300 and inspect /dev/loop0* at that point; see if loop1p0 etc exist, and why they're not expanded by shell globs in the `for` command below.

**Comment by mhwasil** [comment]
Sorry, I was not in my office yesterday already.
I tried to print the /dev/loop0* in the for loop
```
root@server:/srv# ltsp image debian
Running: losetup /dev/loop0 /srv/ltsp/debian.img
¨debug shell¨
/dev/loop0 /dev/loop0p5
blkid: error: /dev/loop0p*: No such file or directory
LTSP command failed: blkid -po export /dev/loop0p*
Aborting ltsp
I don't know how to mount /srv/ltsp/debian.img
```
and there is no loop1p0.
The page for [IRC](https://github.com/ltsp/ltsp/issues/ts.sch.gr/repo/irc/) is not found.

**Comment by alkisg** [comment]
Hi, go to https://ltsp.org and click the IRC channel link.

**Comment by alkisg** [comment]
This one was tricky. Long explanation ahead.

When mounting an image, we want to call `losetup -P` so that it also scans for partitions. So, not only /dev/loop0 will be created, but /dev/loop0p1, /dev/loop0p2 etc too.

There are actually three versions of losetup:

- The one provided by the mount package supports -P
- The busybox losetup only supports -P since [May](https://bugs.busybox.net/show_bug.cgi?id=11941) [2019](https://github.com/mirror/busybox/commit/726cbb1be8620496cdf05d23bd98bdeb0983b4f0)
- The klibc losetup doesn't support -P

If the losetup that we have available doesn't support -P, then we want to run `partprobe` after `losetup`.

The specific problem here was that @mhwasil had a very fast nvme hard drive, and partprobe there was actually returning before the /dev/loop0p* nodes were created. If we inserted a `sleep 0.1` after the partprobe, all was well.

Additionally to all the above, if `modprobe loop max_part=9` is executed, then the loop partition scanner is automatically enabled, so there's no need to call partprobe at all.

I will restructure the code so that it avoid the partprobe/nvme race condition.

**Comment by alkisg** [comment]
Thanks, fix committed in 4759d1f430addfdbfd3de3580e42575402ff1dd2; I also sent a build to the proposed PPA so it'll be possible to test it from there in a bit.

**Comment by ITaluone** [comment]
Hi 

I have the same problem :)

`blkid /srv/ltsp/debian.img` prints nothing

**Comment by alkisg** [comment]
You have the same problem, i.e. you symlinked your VM to /srv/ltsp/debian.img?
Where is your original VM file, e.g. /path/to/vm-flat.vmdk?
What is the output of `sudo blkid /path/to/vm-flat.vmdk`?

**Comment by ITaluone** [comment]
not quite.. I have symlinked `~/VirtualBox VMs/debian-pxe-default/debian-pxe.default.vmdk` to `/srv/ltsp/debian-pxe-default.img`

Output from `blkid debian-pxe-default.vmdk` is also nothing

If I enter `echo $? `after this command it prints `2`

I think I missunderstand what the `vm-flat.vmdk` should be? Whats means "flat"?

**Comment by alkisg** [comment]
@ITaluone please search for the word "flat" in our discussions, this issue has been discussed many times:

https://github.com/ltsp/ltsp/discussions?discussions_q=flat
