### ISSUE TITLE
Debian Buster 64 bit with two nics. Client cannot get ip from dhcp server on lan nic.

### ISSUE THREAD

**Issue by rkwesk** [ltsp/ltsp#12]
Server has old style bios and two nics:

root@buster64dualnicltsp19:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:01:02:05:e7:43 brd ff:ff:ff:ff:ff:ff
    inet 10.72.251.201/24 brd 10.72.251.255 scope global dynamic noprefixroute enp1s2
       valid_lft 1814141sec preferred_lft 1814141sec
    inet6 2a02:587:2d24:1900:81b7:1ea7:c531:bbf7/64 scope global dynamic noprefixroute
       valid_lft 63631sec preferred_lft 63631sec
    inet6 fe80::11bd:1d2f:bf11:d9cf/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: enp1s5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1a:4d:25:fc:65 brd ff:ff:ff:ff:ff:ff
    inet 198.192.67.1/24 brd 198.192.67.255 scope global noprefixroute enp1s5
       valid_lft forever preferred_lft forever
    inet6 fe80::9a15:7128:7759:3581/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

network manager editor is set for lan to simple manual ip
without sharing with other computers. Server is rebooted and
dnsmasq.service starts without error.

However, though all the rest of the install steps are successfully
done I then connect a client. But this client cannot get an ip from
dnsmasq!

{{{tail -f /var/log/syslog}}}

buster64dualnicltsp19 dnsmasq-dhcp[459]: no address range available
for DHCP request via enp1s5
several times and client gives up.

Richard

**Comment by alkisg** [comment]
Hi Richard,

you're using a wrong ip of 198.192.67.1/24 instead of 192.168.67.1/24.

**Comment by rkwesk** [comment]
Ah. Thank you. I will now check how the fat client connects and runs!
Richard

    On Saturday, August 24, 2019, 6:33:44 PM UTC, Alkis Georgopoulos <notifications@github.com> wrote:  
 
 
Hi Richard,

you're using a wrong ip of 198.192.67.1/24 instead of 192.168.67.1/24.

**Comment by rkwesk** [comment]
I changed the lan ip with network manager but the client still cannot get an ip.

I even reran ltsp initrd and then rebooted the server, but still the same log that the client cannot get an ip.

root@buster64dualnicltsp19:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1a:4d:25:fc:65 brd ff:ff:ff:ff:ff:ff
    inet 192.198.67.1/24 brd 192.198.67.255 scope global noprefixroute enp1s5
       valid_lft forever preferred_lft forever
    inet6 fe80::9a15:7128:7759:3581/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: enp1s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:01:02:05:e7:43 brd ff:ff:ff:ff:ff:ff
    inet 10.72.251.201/24 brd 10.72.251.255 scope global dynamic noprefixroute enp1s2
       valid_lft 1813991sec preferred_lft 1813991sec
    inet6 2a02:587:2d24:1900:81b7:1ea7:c531:bbf7/64 scope global dynamic noprefixroute
       valid_lft 58855sec preferred_lft 58855sec
    inet6 fe80::11bd:1d2f:bf11:d9cf/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

and

Aug 24 22:45:32 buster64dualnicltsp19 dnsmasq-dhcp[458]: no address range available for DHCP request via enp1s5
Aug 24 22:45:34 buster64dualnicltsp19 dnsmasq-dhcp[458]: no address range available for DHCP request via enp1s5
Aug 24 22:45:38 buster64dualnicltsp19 dnsmasq-dhcp[458]: no address range available for DHCP request via enp1s5
Aug 24 22:45:46 buster64dualnicltsp19 dnsmasq-dhcp[458]: no address range available for DHCP request via enp1s5

Richard

**Comment by alkisg** [comment]
Richard the IP is still wrong, it's 192.198 instead of 192.168.

**Comment by rkwesk** [comment]
Sorry. My bad

**Comment by rkwesk** [comment]
Since code is to be added in /etc/NetworkManager/dispatcher.d I should wait before pursuing this further?

Richard

**Comment by alkisg** [comment]
You can follow the official LTSP 5 installation steps for 2 NIC setups, which used the sch-scripts script for NAT:

http://wiki.ltsp.org/wiki/Installation/Ubuntu

I.e. currently it's the same as it always was; in a couple of days it'll be even easier and that sch-scripts step won't be needed anymore. Your choice if you want to wait or not. :smiley_cat:
