### ISSUE TITLE
Enable NAT, disable flow control

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#13]
Many network switches come with an "ethernet flow control: enabled" setting, which can severely hurt the network performance: if the LTSP server<=>switch connection is gigabit, and one or more client<=>switch connections are 100 Mbps, then when flow control is enabled, the server will effectively be sending at 100 Mbps to the clients instead of 1000 Mbps.

The [sch-scripts if-up script](https://gitlab.com/sch-scripts/sch-scripts/blob/master/debian/sch-scripts.if-up) contains code that disables ethernet flow control on the server NIC.

Additionally, it contains code to enable NAT on the 192.168.67.x network, so that the clients can access the Internet in 2-NIC LTSP setups.

Unfortunately, the if-up.d (ifupdown) hook is getting deprecated, so the script should be optimized to be able to run from /etc/NetworkManager/dispatcher.d/ as well.

**Comment by rkwesk** [comment]
If I understand this now we should wait for the /etc/NetworkManager/dispatcher.d to have code added before attempting to setup a server with two nics.

Richard

**Comment by alkisg** [comment]
The official LTSP5 installation instructions involved a "wget sch-scripts" command to do NAT:

http://wiki.ltsp.org/wiki/Installation/Ubuntu

Nothing changed so far; new LTSP users can also use that sch-scripts script to do NAT in dual NIC setups.

But in a couple of days, it will be integrated in the new LTSP, so that `wget` step won't be needed at all. Sysadmins can choose if they want to run one wget command now like they always did, or wait a couple of days.

**Comment by rkwesk** [comment]
Is this any help? It uses systemd.


  {{{https://cgit.freedesktop.org/systemd/systemd/commit/?id=5a8bcb674f71a20e95df55319b34c556638378ce}}}
  networkd: add minimal IP forwarding and masquerading support to .network files

**Comment by alkisg** [comment]
Thank you Richard, yes, this would help people that use systemd-networkd, i.e. ...I think Ubuntu/Debian server users and Fedora users, currently.

Debian and Ubuntu desktops usually use network manager, i.e. no .network files involved.
Additionally, it wouldn't solve the flow control issue.

So I think it'll be best to go on with implementing this ^, and make a note of the [IPForward/IPMasquerade](https://www.freedesktop.org/software/systemd/man/systemd.network.html) settings for people using systemd-networkd, where the network-manager dispatcher script won't take effect.

**Comment by rkwesk** [comment]
If you haven't seen this already....

https://wiki.debian.org/SystemdNetworkd

Richard

**Comment by enaut** [comment]
@alkisg I think systemd-networkd is not default in any distro (at least not fedora server). But it is way easier to configure and set up. I really prefer it over NetworkManager. The first thing I do with every server is to switch to systemd-networkd.

**Comment by alkisg** [comment]
Guys we really don't want to enforce ifupdown/network-manager/systemd-networkd to our users.
If at some point systemd-networkd is default in both Debian and Ubuntu, sure, we can rely on it, but until then, we want to support at least the various default setups.

Currently we have two options on where to run the flow control / NAT code:
1. From /etc/network/if-up.d/ltsp. This also works if ifupdown isn't installed and network-manager is, as /etc/NetworkManager/dispatcher.d/01-ifupdown runs those scripts anyway. I'm not sure if it'll work if one removes both ifupdown and network-manager, and installs systemd-networkd.
2. From a /lib/systemd/system/ltsp.service unit, that defines `After=network-online.target` and `Wants=network-online.target`. This would run once when the server gets online, and would disable flow control on all interfaces, and additionally enable NAT if it sees 192.168.67.1. The down side there is that the 192.168.67.1 IP must exist at that time; if one connects the internal NIC later on, they won't get NAT unless they manually run `systemctl restart ltsp`.

I'm starting to implement "2"; if someone thinks it's a bad idea, ping! :wink:

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/60486fde6444fc6af92ff8fcea484a0a7226209e.

- It disables flow control for all interfaces.
- IF one of the server IPs is 192.168.67.1 when the server boots, it enables NAT. If 192.168.67.1 only becomes available later, the user has to manually run `systemctl restart ltsp` then. If this is inconvenient, we may put an additional hook in ifupdown or NetworkManager, or document how people using systemd-networkd would do it.
- It's now possible to use `POST_SERVICE_SOMETHING="jetpipe xxx"` parameters in ltsp.conf to start things when the server or the clients boot, similar to rc.local.

I've just triggered a build in launchpad, it should be available for testing in a few minutes.

**Comment by alkisg** [comment]
Ah, it might be best to provide an ltsp.conf parameter to enable or disable NAT:

```shell
[server]
NAT=1
```

So by default NAT would be autodetected by checking if IP=192.168.67.1 on boot, but it could also be enforced to NAT=1 for the cases where the IP might not yet be set when the ltsp service starts.

Reopening...

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/b3878c541f72fcb8426fce3b024989bb9cfdb486.

Triggering new PPA build...
