### ISSUE TITLE
Investigate possible regressions from NBD to NFS root change

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#132]
Investigate what happens when the clients are online, and the administrator runs `ltsp image /`. x86_64.img gets renamed to x86_64.old, but will the clients then continue accessing the old image, or does NFS get confused and return parts of the new image?
What if the server gets restarted?

Maybe x86_64.img should always be a symlink to images named like x86_64-$(date)?

**Comment by alkisg** [comment]
Another reason to name the images `x86_64-$(date)` is that then rsyncing /srv/ltsp between servers is more efficient, as there's no need to re-transfer x86_64.img just because it got renamed to x86_64.img.old.

**Comment by alkisg** [comment]
I tested and everything seems to work properly.

Except when rsync'ing the /srv/ltsp directory between servers; in which case, commands like the following should be used after `ltsp image`, to prevent rsync from overwriting parts of older images with parts of newer images, thus causing chaos:

```shell
namewithdate=$(date -r x86_64.img "+x86_64.img-%Y%m%d%H%M%S")
mv x86_64.img $namewithdate
ln -s $namewithdate x86_64.img
```

**Comment by alkisg** [comment]
I did see a difference between NBD and NFS: now, when deleting an image, clients immediately lose access to it, resulting in SQUASHFS ERRORs. Previously, the space wasn't freed and the image could still be accessed by all clients that had open file handles to it.

I'm not sure if NFS has any option to replicate the NBD behavior there.

The consequence is that we can run `ltsp image` once without any issues at all, but we cannot run it a second time without rebooting the clients that are using the `.old` image, or without manually renaming `.old` to `.old2` so that it doesn't get removed.

**Comment by alkisg** [comment]
TODO: check something like `PRE_INITRD_BOTTOM_REMOUNT="mount -o remount,lock /root"`, to see if it automatically resolves the issue.

**Comment by alkisg** [comment]
Reopening in order to remember to address the TODO above ^. :)

**Comment by dazzacoy** [comment]
Apologies if this is the wrong place to put this.

I am not sure if this is connected to what I am trying to achieve, but for security reasons I have disabled the nfs-server and would 
 prefer to run ltsp with nbd-server. It seems like this option is not available after the rewrite.

are you able to help?

Let me know if you need anything else?

Kind Regards

Daryl

![nfs_mount_failure](https://user-images.githubusercontent.com/83610641/116926775-b641e680-ac52-11eb-872c-e536004fa1fa.png)

**Comment by alkisg** [comment]
Why would you think that a read only NBD server is more safe than a read only NFS server?

NBD had various regressions and stability issues and I wouldn't want to spend time to support it upstream in LTSP.
That said, it should be easy to manually install and configure nbd-server to serve /srv/ltsp/images/x86_64.img, and to replace nfsroot= with nbdroot= in /srv/tftp/ltsp.ipxe. One could write a wiki page about that.

**Comment by dazzacoy** [comment]
Thanks for your quick response. 

I was just going over what results we are getting on an internal scan.  Is it not possible to serve the image over SSHFS or an SSH tunnel with a key on a usb flash drive? or is that just being silly

**Comment by alkisg** [comment]
Please [open a discussion](https://github.com/ltsp/ltsp/discussions) for alternative rootfs options. Please also mention your requirements; for example, if someone is able to hack into your NFS or NBD server, why wouldn't they hack into the TFTP server instead, and offer a modified kernel/initramfs to take over the clients?

**Comment by alkisg** [comment]
I'll sum up my results so far.

Initramfs-tools currently only supports nfs version 3, and only with the klibc `nfsmount` program, not normally with `mount -t nfs...`. But `nfsmount` doesn't support locks; if we run `nfsmount -o lock 192.168.67.1:/srv/ltsp /root`, it reports `mount: Connection timed out`, while dmesg shows `lockd_up: makesock failed, error=-110`.

Trying nfsv4 from the initramfs, `mount -t nfs -o vers=4 192.168.67.1:/srv/ltsp /root` reports: `mount: NFSv4 not supported`.

It *is* possible to mount /srv/ltsp and lock images/x86_64.img using nfsv4 later on, e.g. on POST_INIT, but if the image is deleted on the server, the NFSv3 access to it is lost, even if the NFSv4 access is still valid. So locking can only happen properly in initramfs-bottom.

Renaming the image on the server is not a problem; it seems that the inode is used while the image is mounted.

All this means that there *is* a regression from NBD to NFSv3 rootfs, regarding locks and image deletion. We can't work around it properly due to restrictions in initramfs-tools (while e.g. the kernel itself and dracut do support nfsv4 booting).

A workaround can be offered by:

- creating dated ltsp images (e.g. /srv/ltsp/images/x86_64-20211212-084032.img),
- using a symlink for x86_64.img,
- allowing `ltsp image -r` to fallback to any older image,
- and introducing a new option e.g. KEEP_LTSP_IMAGES which would mean "after creating a new ltsp image, keep up to xxx older ltsp images" or "keep all images that are up to xxx days old".

I'll close this issue, and if there's need for the workaround, it'll be tracked elsewhere.
