### ISSUE TITLE
Add multiseat client support

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#133]
Please add multiseat client support to the new LTSP, like the old LTSP5 had.

**Comment by alkisg** [comment]
Supported in d34a142b22e08228de71324ca1d7f022a5031bd2, please test.

**Comment by fottsia** [comment]
It appears to work fine, thanks.

**Comment by alkisg** [comment]
The following ltsp.conf code automatically enabled multiseat in all my tests, without having to specifying any udev rules manually:

```shell
[clients]
...
INCLUDE=MULTISEAT

[MULTISEAT]
local minbusnum count busnum

    minbusnum="z"
    count=0
    while read -r busnum; do
        count=$((count+1))
        busnum=${busnum%*/boot_vga}
        busnum=${busnum#/sys}
        # busnum=${busnum##*/}
        test "$busnum" "<" "$minbusnum" && minbusnum=$busnum
    done <<EOF
$(find /sys/devices/pci* -name boot_vga)
EOF
    if [ "$count" -ge 2 ]; then
        UDEV_SEAT_1_GRAPHICS="${minbusnum}*"
        UDEV_SEAT_1_ODD_USB_PORTS="${UDEV_SEAT_1_ODD_USB_PORTS:-*/usb?/?-[1,3,5,7,9,11,13,15,17,19]/*}"
    else
        unset UDEV_SEAT_1_GRAPHICS
        unset UDEV_SEAT_1_ODD_USB_PORTS
    fi
```

It might be worth to upstream it after it receives some more real-world testing.

**Comment by alkisg** [comment]
Committed the multiseat autodetection code, @fottsia could you please test it and close the issue if it works?

**Comment by fottsia** [comment]
It works for me, closing...
