### ISSUE TITLE
ltsp-chroot is required when creating images inside docker.

### ISSUE THREAD

**Issue by casibbald** [ltsp/ltsp#135]
Process:
debootstrap --arch arm64 xenial /opt/ltsp/arm64

`
$ ltsp image /opt/ltsp/arm64
> Running: mount -t tmpfs -o mode=0755 tmpfs /tmp/tmp.Iu2Fk6Pa1N/tmpfs
> mount: /tmp/tmp.Iu2Fk6Pa1N/tmpfs: permission denied.
> LTSP command failed: mount -t tmpfs -o mode=0755 tmpfs /tmp/tmp.Iu2Fk6Pa1N/tmpfs
> Aborting ltsp
`

Previously on 16.04, we were able to run this with ltsp-chroot
ltsp-chroot: deprecated; maybe reincluded if there's need

for example:
`RUN ltsp-chroot apt-get -y install ltsp-client-core`

Additionally, we need to be able to run the following:
`
ltsp-chroot apt-get -y install \
      software-properties-common \
      apt-transport-https \
      ca-certificates \
      ssh \
      bridge-utils \
      pv \
      jq \
      vlan \
      bash-completion \
      screen \
      vim \
      mc \
      lm-sensors \
      htop \
      jnettop \
      rsync \
      curl \
      wget \
      tcpdump \
      arping \
      apparmor-utils \
      nfs-common \
      telnet \
      sysstat \
      ipvsadm \
      ipset \
      make

# Install kernel
RUN ltsp-chroot apt-get -y install linux-generic-hwe-16.04
`

Full file here:
https://github.com/georgia-pipeline/ltsp/blob/master/ltsp-basesystem/DockerfileArm64

**Comment by alkisg** [comment]
Hi, there are no plans to add chroot management tools in the new LTSP at this time.
There are dozens of other tools that do that, chroots aren't specific to LTSP.

LTSP officially supports chroots as image sources, but it won't be involved in their maintenance.
