### ISSUE TITLE
Slow NFS speed after fixing #43

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#136]
Fixing #43 caused yet another regression: LTSP clients get much slower NFS root access than they should.
To test if you're affected, run the following commands as root on the client:

```shell
echo 3 > /proc/sys/vm/drop_caches
dd if=/dev/loop0 of=/dev/null bs=1M status=progress
```

It should be roughly equal to the client <=> server network speed. For example, a gigabit client should show around 100 MB/sec, yet in my test it only showed 10 MB/sec.

A workaround is to put this in ltsp.conf, and run `ltsp initrd`:

```shell
[clients]
READ_AHEAD_KB="128"
```

Then reboot the clients and do the benchmark commands again.

I believe the underlying problem is that I didn't update the set_readahead function after fixing #43, so now the NFS mount has a different read ahead value than its tmpfs overlay.
Anyway, since I did manage to get the NFS readahead fix upstream in the kernel, we can just make the 128 value default, as it already is in the newest kernels. That way in the future LTSP won't need to bother with read ahead at all.

I'll see if I can push a new LTSP version to Ubuntu 20.04 later on.

**Comment by jeremy-walker** [comment]
I tried the I/O test, and I'm seeing 93 MB/s <=> 110 MB/s without the `READ_AHEAD_KB` change in `/etc/ltsp.conf`.

But I had to change the `dd` command as follows:

```
$ dd if=/dev/loop0 of=./test.img bs=1M status=progress
```

For some reason, setting the output to /dev/null resulted in a 0 records in, 0 records out, 0 bytes copied.

**Comment by alkisg** [comment]
What's the output of the following commands on the client?

```shell
df -h
grep nfs /proc/self/mountinfo
grep . /sys/class/bdi/*/read_ahead_kb
losetup -a
cat /proc/cmdline
```

**Comment by alkisg** [comment]
Ah, actually, I forgot that you're using Odroid.
Raspbian, and I think Odroid too, do not use an initramfs at all, so they do not even have an INITRD_BOTTOM boot phase at all; they're not affected by this issue.

**Comment by alkisg** [comment]
Hrm... it's probably best if I close this one, and reopen #27. Doing so.
