### ISSUE TITLE
Generate ltsp.ipxe from ltsp.conf

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#14]
My initial idea was that ltsp.ipxe can be so complicated that it would be best to generate it once, and then let the sysadmin maintain it by manual editing. The sysadmin might even put hostname or ltsp.param= entries there, and not use ltsp.conf by default at all.

I'm now thinking that the opposite is better; for sysadmins to maintain a single file, ltsp.conf, and have ltsp.ipxe auto-generated for all but the most weird use cases.

To that end, I'll try to support the following options in ltsp.conf:

- IPXE_X64_32="Debian Buster" would mean "use Debian Buster as the menu name for the chroot x64_32"
- MENU_TIMEOUT="6000" would use that timeout
- IMG="x64_32" would set the default image for the client with this mac address
- CMDLINE="nolapic noapic" would use those kernel cmdline parameters for the client with this mac address

**Comment by alkisg** [comment]
For the first part, IPXE_X64_32, we'll use this awk command to convert from image-name.img to IPXE_IMAGE_NAME:

```shell
# img1="My-chroot"
# echo "$img1" | awk '{ var=toupper($0); gsub("[^A-Z0-9]", "_", var); print "IPXE_" var }'
IPXE_MY_CHROOT
# img2="My-chroot.img"
# echo "$img2" | awk '{ var=toupper($0); gsub("[^A-Z0-9]", "_", var); print "IPXE_" var }'
IPXE_MY_CHROOT_IMG
```

I.e. the image name will be converted to uppercase, and invalid characters to underscores. So in this case the sysadmin would put in ltsp.conf:

```shell
IPXE_MY_CHROOT="Netboot Debian Buster (chroot)"
IPXE_MY_CHROOT_IMG="Netboot Debian Buster (squashfs)"
```

**Comment by MAccadia** [comment]
We do use a custom boot pxelinux menu allowing :
  * booting on the local disk (windows)
  * selecting an alternate LTSP server to boot from (for beta-testing or specific features)

We also do some branding. I don't mind maintaining a custom ipxe config though.

**Comment by alkisg** [comment]
Thank you MAccadia, yeah, people that want that level of customization could use the autogenerated ltsp.ipxe as a starting point, but would probably need to maintain it manually after that.

That said, booting to a local disk is already supported by the [two last ipxe menu options](https://raw.githubusercontent.com/wiki/ltsp/ltsp/images/ltsp-ipxe.png),
and if it was possible to put all your customizations in a single "paragraph/place" in ltsp.ipxe, then I could implement an IPXE_INCLUDE="additional-file" parameter in ltsp.conf, that would insert your customizations file in the generated ipxe...

**Comment by MAccadia** [comment]
> local disk is already supported by the two last ipxe menu options
great, I won't need to figure out how to do that with ipxe.

As for `IPXE_INCLUDE="additional-file"`, it might be handy, but on the other hand, if a user is able to write a custom ipxe config, he can as well maintain the whole file which don't change that much if we use initrd and vmlinuz symlinks to point to the last ones.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/ac93e91f85f6f4ce30f26d0b9d81c3a0ff69efaa.
