### ISSUE TITLE
docker fails on client 

### ISSUE THREAD

**Issue by brcisna** [ltsp/ltsp#140]
Hello All,

Started to try and work with docker again after a couple years for some python projects. Can not get docker to work or get started on client. Just a guess it has something to do with the overlay/metacopy parameter. Just an unscientific guess.
Docker will simply not start on client but works fine on server. Am very rusty at docker so am stumped.

Thank You

**Comment by alkisg** [comment]
Personally I'm not using docker, so I can't comment on this one...

**Comment by kvaps** [comment]
@brcisna docker can't work on top of overlayfs, but it is working fine on to of tmpfs, so simple adding:
```
FSTAB_DOCKER = "tmpfs /var/lib/docker   tmpfs noatime,nodiratime,x-systemd.wanted-by=docker.service 0 0"
```
Will solve your problem :-)

**Comment by alkisg** [comment]
No action seems to be needed in the LTSP code base for this issue, closing...
