### ISSUE TITLE
Questions on dual nic install

### ISSUE THREAD

**Issue by rkwesk** [ltsp/ltsp#15]
For the install I used a recent Buster netinst iso, chose expert install and only had the installer put the basic system and grub.

Rebooted now on basic system, edited /etc/network/interfaces

```shell
root@buster64dualnicltsp19:~# ip a; cat /etc/network/interfaces

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1a:4d:25:fc:65 brd ff:ff:ff:ff:ff:ff
    inet 192.168.67.1/24 brd 192.168.67.255 scope global enp1s5
       valid_lft forever preferred_lft forever
    inet6 fe80::21a:4dff:fe25:fc65/64 scope link 
       valid_lft forever preferred_lft forever
3: enp1s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:01:02:05:e7:43 brd ff:ff:ff:ff:ff:ff
    inet 10.72.251.201/24 brd 10.72.251.255 scope global dynamic enp1s2
       valid_lft 1807482sec preferred_lft 1807482sec
    inet6 2a02:587:2d24:1900:201:2ff:fe05:e743/64 scope global dynamic mngtmpaddr 
       valid_lft 77418sec preferred_lft 77418sec
    inet6 fe80::201:2ff:fe05:e743/64 scope link 
       valid_lft forever preferred_lft forever
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The wan interface
allow-hotplug enp1s2
iface enp1s2 inet dhcp
# This is an autoconfigured IPv6 interface
#iface enp1s2 inet6 auto

# The lan interface
allow-hotplug enp1s5
iface enp1s5 inet static
address 192.168.67.1
netmask 255.255.255.0
broadcast 192.168.67.255
# This is an autoconfigured IPv6 interface
#iface enp1s2 inet6 auto

root@buster64dualnicltsp19:~# cat /etc/apt/sources.list
deb http://deb.debian.org/debian/ buster main non-free contrib
deb http://security.debian.org/debian-security buster/updates main contrib non-free
deb http://deb.debian.org/debian/ buster-updates main contrib non-free
deb http://deb.debian.org/debian/ buster-backports main contrib non-free
```

Reboot again update and full upgrade and install xorg mate lightdm firefox-esr rsync wget

NOTE - The packages networkd-dispatcher, network-manager-gnome and wicd are NOT installed

Run the steps from the wiki to install ltsp19

```shell
root@buster64dualnicltsp19:~# ltsp info

LTSP version: 19.08-1~201908270954~ubuntu18.04.1

SERVER XSESSIONS: lightdm-xsession.desktop  mate.desktop

SERVER OS: PRETTY_NAME="Debian GNU/Linux 10 (buster)"

CHROOTS:

VMs:

IMAGES:
x86_64
```

No suprise that flow control was not altered since the above mentioned packages were not installed

```shell
root@buster64dualnicltsp19:~# journalctl -xe | grep flow

Aug 27 15:27:09 buster64dualnicltsp19 kernel: r8169 0000:01:05.0 enp1s5: Link is Up - 100Mbps/Full - flow control rx/tx
Aug 27 15:27:10 buster64dualnicltsp19 ltsp[411]: Couldn't disable flow control for enp1s2
Aug 27 15:27:10 buster64dualnicltsp19 ltsp[411]: Couldn't disable flow control for enp1s5

client on lan has normal Internet access, nat seemed to work great, but the older ways...?

root@buster64dualnicltsp19:~# iptables -L

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

I have two questions about what is and is not in /etc/dnsmasq.d/ltsp-dnsmasq.conf

1) With ltsp5 didn't we run dhcp proxy on the wan even when there was a separate lan?

2) It seems harmless but why is there a bogus ip on the line

dhcp-option=option:dns-server,192.168.1.1,<my router>

Last, but not least, (by chance) at the moment I started the client I suddenly realized that I hadn't added a second user so without stopping anything I went back to add it. The client couldn't see it (even rebooting it) until I reran

```ltsp initrd```

So you might want to add to the wiki that

"and if you add or delete users on server."

Richard

**Comment by alkisg** [comment]
Hi Richard!

About markdown syntax: multiline shell output goes inside triple backticks `, not triple { and }.
I edited your comment above; you can click edit too and see what I did there.

About flow control: I think you're missing the "ethtool" tool, I need to at least document it or put it in the Suggests list or something.

About ltsp/issues vs community/issues: whatever results in LTSP code changes goes in ltsp/issues (=bug), while whatever doesn't result in LTSP code changes goes in community/issues (=discussion).

So this one is a bug, since it will result in adding "ethtool" to the dependencies, and "ltsp initrd" to the documentation as you said in the last paragraph.

About this: "With ltsp5 didn't we run dhcp proxy on the wan even when there was a separate lan?"
The answer is yes for both LTSP5 and LTSP19.

About this: "It seems harmless but why is there a bogus ip on the line dhcp-option="

This is what was detected as your DNS server when you ran `ltsp dnsmasq`, either from systemd-resolve or from /etc/resolv.conf. If this isn't correct, we need to see where it came from.

Thanks!

**Comment by rkwesk** [comment]
Yes, ethtool was not installed. So I updated which pulled in a newer ltsp pkg and installed ethtool, ran ltsp initrd and rebooted.

Still

'''root@buster64dualnicltsp19:~# journalctl -xe | grep flow'''

Aug 28 18:51:36 buster64dualnicltsp19 kernel: r8169 0000:01:05.0 enp1s5: Link is Up - 100Mbps/Full - flow control rx/tx
Aug 28 18:51:37 buster64dualnicltsp19 ltsp[438]: Couldn't disable flow control for enp1s2
Aug 28 18:51:38 buster64dualnicltsp19 ltsp[438]: Couldn't disable flow control for enp1s5

Remember the pkgs  networkd-dispatcher, network-manager-gnome and wicd are NOT installed.

Richard

**Comment by alkisg** [comment]
Richard also try:

```
apt install net-tools
```

**Comment by rkwesk** [comment]
Yes. I installed net-tools and ran ltsp initrd (should I have to?) and rebooted. It works but doesn't use ethtool.

'''root@buster64dualnicltsp19:~# journalctl -xe | grep flow'''
Aug 29 10:25:16 buster64dualnicltsp19 kernel: r8169 0000:01:05.0 enp1s5: Link is Up - 100Mbps/Full - flow control rx/tx
Aug 29 10:25:20 buster64dualnicltsp19 ltsp[446]: Disabled flow control for enp1s5 using mii-tool
Aug 29 10:25:21 buster64dualnicltsp19 kernel: r8169 0000:01:05.0 enp1s5: Link is Up - 100Mbps/Full - flow control rx/tx

Richard

**Comment by alkisg** [comment]
Great, so https://github.com/ltsp/ltsp/commit/d5d24aa0292be39e02335e71dc5f3df8a8fabd35 addressed all the issues mentioned here.
