### ISSUE TITLE
AUTOLOGIN blocks boot in unknown clients

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#157]
If I put this line in ltsp.conf:

```shell
[clients]
AUTOLOGIN="^pc\([0-9]*\)$/guest\1"
```

It works fine if my clients are actually named pc01, pc02 etc.
But if I boot a client that is unnamed, e.g. ltsp123, then LTSP boot stops with the following messages:

> LTSP command failed: grep -q ^pc\([0-9*\)$
> Aborting ltsp
> LTSP boot error! Enable DEBUG_SHELL to troubleshoot!

**Comment by alkisg** [comment]
Thanks, fix committed in 9052790.
