### ISSUE TITLE
Setting up local printers on the clients

### ISSUE THREAD

**Issue by samthelion** [ltsp/ltsp#158]
Hi, I've been trying to set up local printers on LTSP clients (using Ubuntu 20.04.1, with latest ltsp from ppa, chrootless environment). The Issue #8 was really helpful helping me understand how the new LTSP works but I'm , clearly, missing something. Can somebody point me out in the right direction?

Best regards!

**Comment by alkisg** [comment]
You're supposed to put CUPS_SERVER=localhost in ltsp.conf for that. Then LTSP clients behave like standalone clients, i.e. they can share their local printers or see other shared printers from the network.

**Comment by samthelion** [comment]
> You're supposed to put CUPS_SERVER=localhost in ltsp.conf for that. Then LTSP clients behave like standalone clients, i.e. they can share their local printers or see other shared printers from the network.

But then I'll have to set up every printer after the client starts, right?

**Comment by alkisg** [comment]
If the image has the drivers, the printers should be automatically activated when cups starts.
If you want to forward the printer ports to the server, like LTSP5 did with jetpipe, you can either manually download jetpipe.py, or install and use [p910nd](https://manpages.debian.org/p910nd) instead of jetpipe.

**Comment by samthelion** [comment]
Ok, I will try that soon but, just in case I need to use p910nd, let's sketch out the procedure of using p910nd with the new LTSP. I remember that back in the days of LTSP5 printers were added in the lts.conf, but things have changed, so the right steps to do now would be:

1. Install p910nd
2. Update image
3. ?

**Comment by alkisg** [comment]
3. If p910nd has a systemd service etc, it will just need to be enabled.
If it's a standalone program like jetpipe.py, you'd run it via ltsp.conf like
POST_SERVICE_P910ND="p910nd parms &"

**Comment by samthelion** [comment]
4. Go to CUPS admin / Add Printer
5. Select 'AppSocket/HP JetDirect'
6. Fill connection with the right data "socket://<client_IP>:<port>", port being 910{0..9}
7. Setup driver and other settings...

But still, I need to tell p910nd which printer corresponds to a specific port. Let's assume that all my printers are USB printers and that every client will have only one printer connected to it.

**Comment by alkisg** [comment]
This is the "params" in the p910nd command line; you can specify the printer path from there, e.g. /dev/usb/lp0. Same with jetpipe.py.
