### ISSUE TITLE
Chrootless image generation fails on Linux kernel 5.2 (and newer)

### ISSUE THREAD

**Issue by Uumas** [ltsp/ltsp#17]
Terminal output: https://pastebin.com/TkVps9BE
Relevant dmesg line: `overlayfs: overlapping upperdir path`
Relevant kernel patch: https://lkml.org/lkml/2019/6/24/445

**Comment by alkisg** [comment]
Thank you @Uumas, fix committed in https://github.com/ltsp/ltsp/commit/4fdc2dfa6c2d5211978ea01b9704f45f3d9fb987.
