### ISSUE TITLE
Gnome-keyring fails to start when user has never logged into the server

### ISSUE THREAD

**Issue by enaut** [ltsp/ltsp#22]
I just created a batch of users for my students and noticed they take really long to log in.

The culprint seems to be that they have never been logged in on the server.

gnome-keyring fails with a timeout and it creates thousands of files in 
/home/user/.local/share/keyrings:

```bash
ls /home/*/.local/share/keyrings
/home/userx/.local/share/keyrings:
login.keyring.temp-1961701082  login.keyring.temp-999846504
login.keyring.temp-1961701640  login.keyring.temp-999903686
login.keyring.temp-1961728055  login.keyring.temp-999945769
login.keyring.temp-1961781194  login.keyring.temp-999975854
...
```

gnome-keyring fails to create the usual file `login.keyring` and `user.keystore`.

I think this is a ltsp issue as this occurs only when logging in via ltsp (authenticated and mounted with ssh).

**Comment by alkisg** [comment]
This is an old gnome-keyring bug, I've reported it there:
https://bugzilla.gnome.org/show_bug.cgi?id=730587

The new LTSP automatically runs `chmod -x /usr/bin/gnome-keyring /usr/bin/gnome-keyring-daemon` on the first login attempt, if it doesn't detect NFS in /etc/fstab, which means that SSHFS is used.

Check your clients after first login, is gnome-keyring marked as NOT executable?
If not, is NFS mentioned in the client /etc/fstab?

**Comment by alkisg** [comment]
The related lines in the pamltsp code are there:
https://github.com/ltsp/ltsp/blob/master/ltsp/client/login/pamltsp#L88

**Comment by enaut** [comment]
ah did you change something in the latest version? I upgraded and now it works (without gnome-keyring)... Thank you for your time.
