### ISSUE TITLE
Default to ipxe.pxe and ipxe.efi

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#29]
Currently LTSP uses undionly.kpxe (size 66K) and snponly.efi (156K).
These are supposed to reuse the PXE stack as the network driver, so they have small sizes.
The problem is that in some cases (maybe 10%?) they're unstable, e.g. hanging at "Initializing devices...".
IPXE offers two other files that contain both the PXE driver but also all the iPXE NIC drivers: ipxe.pxe (332K) and ipxe.efi (959K).
These are larger and may make booting a second slower, but they're more stable.

I think `ltsp ipxe` should default to these, and only document in the man page that someone may manually download and use undionly.kpxe/snponly.efi.

**Comment by rkwesk** [comment]
I agree that stability is more important than speed. Surely after updating to such a patched ltsp the command

   ```ltsp -o ipxe
```
will be needed!

Richard

**Comment by alkisg** [comment]
Richard have a read at the markdown syntax:
https://guides.github.com/features/mastering-markdown/

**Comment by alkisg** [comment]
After some discussion in the #ipxe channel, I think it'll be best not to do that.
The UNDI/SNP variants will boot some onboard NICs that the "all drivers" variants won't be able to boot, as they unload the PXE stack before trying the native iPXE drivers.
And, the iPXE developers are interested in solving UNDI/SNP issues, so we can report them to them.

I'm closing this for now; might reopen if we find out that UNDI/SNP fail in too many cases.
