### ISSUE TITLE
sudo command fails on client 

### ISSUE THREAD

**Issue by brcisna** [ltsp/ltsp#337]
Hello All,
Debian Bullseye

After doing numerous updates over the last sveral days rebuilt client image.
I can log into the clients as any user as expected.
The users that i have setup for sudo can no longer run sudo command on client. It does work as usual on the sevrer though. Have never had to troubleshoot this before.
Example:  when i run 'sudo kill -9 ### ' ,, then password entered,,  i   get 'Login incorrect'
I did double check to make sure the sudousers file hasnt been relaced by updates,,,which it has in the pst,,and it is still the same for a few months now.

Also, I did rebuild the client image a second time just to try something, no changes.

Thank You

**Comment by alkisg** [comment]
Can they run `su - user`, to authenticate as themselves?
Also, run `journalctl -f` as root on the client (e.g. via epoptes), then try to run `sudo` as the user, and check what the journal logs have to say about it.

**Comment by brcisna** [comment]
Hi Alkisg,

Thank You for helping out.

When i run the first command on client I get the following :
su - sudousername
Password: 
.Login incorrect.
su: Authentication failure

When I run the second pair of commands you suggested in the journalctl logs i see one line generated,this line:
Nov 26 06:37:12 hostname sshd[243636]: Connection closed by authenticating user sudousername #.#.#.# port 57862 [preauth]

Also adding I know the sudoers file is correct on the server were the two sudousers function as expected,,but I cannot actually see the sudoers file is identical as i cannot get root on client but the dates are identical on each machine so i assume they are both identical. I havent touched this file since server build a little over year ago,other than when it was replaced a few months ago by  by updates and edited at that time since that time has remained the same so im sure it isnt fatfingered in that regard.

Have not changed any firewall rules for several months for a little more info. Have added many many multimedia programs each month as i use this server/client for doing novice video editing for history videos. Cannot picture any of these apps causing sudo problems under the hood.

Googled and dont really see this exact error 'login incorrect' for trying to run sudi command. This just started two days ago. FYI.

Ideas?

Thanks again
