### ISSUE TITLE
incorrect information on the site https://ltsp.org/man/ltsp-initrd/

### ISSUE THREAD

**Issue by renatolsxc** [ltsp/ltsp#341]
on the page has wrong information that leads to a wrong sshfs configuration

in the example setup below
cp /usr/bin/sshfs /etc/ltsp/sshfs-$(uname -m)

the correct is
cp /usr/bin/sshfs /etc/ltsp/bin/sshfs-$(uname -m)

Thank you very much

**Comment by alkisg** [comment]
Indeed, thank you, will fix it in the next release.

Note that this is only needed if someone wants to boot live CDs that don't have the sshfs package installed. Normally one should just install sshfs in the ltsp image/chroot/vm.

**Comment by alkisg** [comment]
Fixed in #588ee6.
