### ISSUE TITLE
Transform INCLUDE into section_call

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#343]
There are 3 problems with sections and INCLUDEs, let's track them all here.

The end goal is:

| Source | Target code |
| - | - |
| [crt-monitor] | section_crt_monitor |
| INCLUDE=crt-monitor | section_call 'crt-monitor' |
| INCLUDE="crt-monitor" | section_call 'crt-monitor' |

While currently, e.g. the last line there is transformed into `section_"crt-monitor"`. It's not using `section_call`, it doesn't strip quotes, and it doesn't transform `[^a-z0-9]` to `_`.

**Comment by alkisg** [comment]
A fourth issue there is that it doesn't allow comments in the section/INCLUDE lines.
I'm hoping the following patch addresses all 4 issues, could someone please test it before I commit it?

```diff
diff --git a/ltsp/common/ltsp/55-config.sh b/ltsp/common/ltsp/55-config.sh
index fb021e2..6849eeb 100644
--- a/ltsp/common/ltsp/55-config.sh
+++ b/ltsp/common/ltsp/55-config.sh
@@ -114,7 +114,8 @@ BEGIN {
 if ($0 ~ /^[ ]*\[[^]]*\]/) {  # [Section]
     print "}\n"
     section=tolower($0)
-    gsub("[][]", "", section)
+    sub("#.*", "", section)
+    gsub("[^-*./:?@_|0-9a-z]", "", section)
     section_id=section
     section_id=prefix section_id
     gsub("[^a-z0-9]", "_", section_id)
@@ -125,8 +126,10 @@ if ($0 ~ /^[ ]*\[[^]]*\]/) {  # [Section]
     list_sections=list_sections "\n" section_id
 } else if (tolower($0) ~ /^include *=/) {  # INCLUDE = xxx
     value=tolower($0)
+    sub("#.*", "", value)
     sub("include *= *", "", value)
-    print prefix value
+    gsub("[^-*./:?@_|0-9a-z]", "", value)
+    print prefix "call \"" value "\""
 } else if ($0 ~ /^[a-zA-Z0-9_]* *=/) {  # VAR = xxx
     value=$0
     sub(" *= *", "=", value)  # remove spaces only around the first =
```

**Comment by fottsia** [comment]
It seems to work fine here.

**Comment by alkisg** [comment]
Thanks, fix committed in  b67e824.

**Comment by vsuojanen** [comment]
I'd like to reopen this:
The client specific sections, shell expression matching should work using MAC address, IP address, but also hostname sections.

When booting the client I configure clients settings under [client] or under MAC [xx:xx:xx:xx] matching multiple clients with HOSTNAME keys - the hostname based sections are not found. Tested this with simple AUTOLOGIN in ltsp.conf 

[ltsp.conf.txt](https://github.com/ltsp/ltsp/files/6173878/ltsp.conf.txt)
the HOSTNAME under [client] and matching is not anywhere the default use case but has worked until this commit

e.x. 
[clients]
HOSTNAME=testme%{IP} or just HOSTNAME=testme
[xx:xx:xx:xx]
HOSTNAME=pc%{IP} or just HOSTNAME=pc

[testme]
AUTOLOGIN=guest

I could use client MAC sections and INCLUDE but for some odd reason I did not get that section call work either. e.x INCLUDE=low_resolution

**Comment by vsuojanen** [comment]
I quickly tested changing from `print prefix "call \"" value "\""` back to `print prefix value`
This seem to find better the hostname specific section

Based on the test I don't know yet what use cases my test actually changed, are the hostname specific sections handled under the same case as include =  ?

**Comment by vsuojanen** [comment]
This works now also:

```
# /bin/sh -n
# LTSP configuration file
# Documentation=man:ltsp.conf(5)

# The special [server] section is evaluated only by the ltsp server
[server]
# Enable NAT on dual NIC servers
# NAT=1
# Provide a full menu name for x86_32.img when `ltsp ipxe` runs
# IPXE_X86_32_IMG="Debian Buster"

#Hides the ipxe menu
MENU_TIMEOUT="-1"

# The special [common] section is evaluated by both the server and ltsp clients
[common]
# Specify an alternative TFTP_DIR
# TFTP_DIR=/var/lib/tftpboot
DEBUG_SHELL=1

# In the special [clients] section, parameters for all clients can be defined.
# Most ltsp.conf parameters should be placed here.
[clients]
# Specify an /etc/fstab line for NFS home; note this is insecure
# FSTAB_HOME="server:/home /home nfs defaults,nolock 0 0"
# HOSTNAME="pc%{IP}" b67e8249 works with section [pc*]
HOSTNAME=pc%{IP}
POST_INIT_ENABLE_EPOPTES_CLIENT="systemctl enable --quiet --root=/ --no-reload epoptes-client"
LIGHTDM_CONF="allow-guest=false"
LIGHTDM_CONF="/etc/ltsp/lightdm.conf"
# In some cases very old client PCs might need longer time to login
RELOGIN_TIMEOUT=3

# [00:15:5d:f7:bf:12]
# HOSTNAME=pc01 b67e8249 works with section [pc01]
# without HOSTNAME works with MAC address section (section [pc01] still included in the config)
# HOSTNAME=pc01 b67e8249 works with section [pc*]
# HOSTNAME=pc01 b67e8249 works with INCLUDE=pc_session and section [pc_session]
# 
# HOSTNAME=pc%{IP} b67e8249 works with section [pc*]
# HOSTNAME="pc%{IP}" b67e8249 works with section [pc*]
# HOSTNAME="pc%{IP}" b67e8249 works with INCLUDE=pc_session and section [pc_session]
# HOSTNAME="pc%{IP}"
# INCLUDE=pc_session

# [192.168.67.*]
# HOSTNAME=pc01 b67e8249 works with section [pc*]
# without HOSTNAME b67e8249 works with INCLUDE=pc_session and section [pc_session]
# HOSTNAME=pc01
# INCLUDE=pc_session

[pc*]
POST_INIT_CREATE_DIRS="
/usr/lib/klibc/bin/nfsmount 192.168.67.1:/home/nfs /mnt
mkdir -p /mnt/$MAC_ADDRESS/home/guest
chown guest:guest /mnt/$MAC_ADDRESS/home/guest
umount /mnt
mkdir -p /etc/guest-template
sed 's|^Exec=|&/etc/ltsp/ltsp-session |' -i /usr/share/xsessions/*.desktop
/usr/lib/klibc/bin/nfsmount -o nolock 192.168.67.1:/home/nfs/$MAC_ADDRESS/home /home
/usr/lib/klibc/bin/nfsmount -o nolock,ro 192.168.67.1:/home/guest /etc/guest-template
"
# Autologin on boot and when logging out
AUTOLOGIN="guest"

# You can also group parameters into named sections and INCLUDE= them elsewhere
[crt_monitor]
# Force EDID and resolution to 1024x768 for clients with old CRT monitors
X_HORIZSYNC="28.0-87.0"
X_VERTREFRESH="43.0-87.0"
X_MODES='"1024x768" "800x600" "640x480"'
```

I had an error in long ltsp.conf configuration closing one clients config value parenthesis  and when debugging with new clean ltsp.conf the I had some other user error (server/image update process not clean or the machine in bad internal virtual network).
