### ISSUE TITLE
Waiting for suspend/resume device

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#346]
While booting an LTSP client with a local hard disk, from an Ubuntu MATE 20.04 server, I get a long delay that shows the following lines, before it finally continues booting successfully:

> Begin: Running /scripts/local-premount ... Begin: Waiting for suspend/resume device ... Begin: Running /scripts/local-block ... done.

**Comment by alkisg** [comment]
Thanks, fix committed in 1f1292d.

Some newer Ubuntu versions use /etc/conf.d/zz-resume-auto instead of /etc/conf.d/resume to store their RESUME= configuration. Let's delete everything all *resume* files in that directory!
