### ISSUE TITLE
Avoid more than 2 login error messages

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#353]
When trying to login via LDAP, if the user password has expired, the following messages show up in the slick-greeter login screen:

> **administrator**
> remote host has disconnected
> .Pamltsp failed to mount home via SSHFS.
> Password expired. Change your password now.
> [*almost hidden password entry box*]

If these 3 error message there were 2 instead, then the password entry box would show up fine; now it's almost hidden.

**Comment by alkisg** [comment]
Thanks, fixed in aac08ce.
Now it should display: 

> **administrator**
> .Pamltsp failed to mount home via SSHFS: remote host has disconnected.
> Password expired. Change your password now.
> [*almost hidden password entry box*]
