### ISSUE TITLE
section_list: not found

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#36]
If /etc/ltsp/ltsp.conf doesn't exist, then `ltsp -o ipxe` shows the following warning:

> /usr/sbin/ltsp: 95: /usr/sbin/ltsp: section_list: not found

It does work correctly even after the warning though.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/d0a2375285108d0d7f181f910901733a82663c16.
