### ISSUE TITLE
Linux LXLE stop web connection after ltsp dnsmasq for 2 NICS

### ISSUE THREAD

**Issue by doguibnu** [ltsp/ltsp#40]
Hello!
I am testing some "thin" distros  for my clients side (it is old). So, when I try to config
ltsp -o dnsmasq -d1 -p0 --dns-server= IPS dns

I lost web connection but the system ping 8.8.8.8 ok for exemple. I see this problem with LXLE and Linux Lite (ubuntu flavor base 64 bits)

With Xubuntu, the system run well, automatic boot on clients but my pain is the navigator 

Thanks for attention

**Comment by alkisg** [comment]
Can you paste the whole output of the command, when you try to run this?

Also, do you lose DNS on the server, the clients, or both?

Finally, what's the output of these commands?

```shell
ls -l /etc/resolv.conf
systemd-resolve --status | grep -A5 'DNS Servers:'

```

**Comment by alkisg** [comment]
Btw, Lubuntu live CD boots with 130 MB RAM occupied, while LXLE live CD boots with 180 MB RAM occupied. So it's heavier, not lighter; and it also contains some old kernels /boot/vmlinuz-4.4-xxx, and even dpkg-bak files there; it doesn't seem very professional...

**Comment by doguibnu** [comment]
> Btw, Lubuntu live CD boots with 130 MB RAM occupied, while LXLE live CD boots with 180 MB RAM occupied. So it's heavier, not lighter; and it also contains some old kernels /boot/vmlinuz-4.4-xxx, and even dpkg-bak files there; it doesn't seem very professional...

Right! So, I will let this distros alone! Thank you Alkis

Does It possible run Ltsp (mean easy mode install) rpm base? I think to try Gecko Linux (opensuse distro base) or maybe Fedora, only for tests

Thanks

**Comment by alkisg** [comment]
No, LTSP currently only supports .deb distributions; someone will need to package it for .rpm too.

Also note that Gecko Linux doesn't even have a 32 bit release, it's only for 64 bit clients...
Didn't you say your clients are old?

**Comment by doguibnu** [comment]
> No, LTSP currently only supports .deb distributions; someone will need to package it for .rpm too.
> 
> Also note that Gecko Linux doesn't even have a 32 bit release, it's only for 64 bit clients...
> Didn't you say your clients are old?

Yes, the client are old but support 64. I do not want use 32 bits for ltsp

**Comment by alkisg** [comment]
With 64bit clients you don't need to look for light distributions...
Debian or Ubuntu with LXDE/MATE/XFCE are more than fine.

But remember, booting those might need 150-200 MB RAM, and then opening a couple of tabs in firefox might need 1 GB RAM; so flavors don't matter much, it's the web itself that's heavy...
