### ISSUE TITLE
q4os (debian base 64 bits) client no connection internet (2 NICS) and no ask user login

### ISSUE THREAD

**Issue by doguibnu** [ltsp/ltsp#41]
Hello!
 I Think found a good distro for LTSP: 
**Q4OS** 

But, there are two problems
First with dnsmasq and other with registered user system

Following this for Debian:
https://github.com/ltsp/ltsp/wiki/ppa

ltsp dnsmasq (2 Nics)
https://github.com/ltsp/ltsp/blob/master/docs/ltsp-dnsmasq.8.md

and all  steps to build the ltsp server nice, ok!

Create other user to test and did the command:
ltsp initrd

So, sometimes after command:
**ltsp -o dnsmasq -d1 -p0 --dns-server=**dns****
Installed /usr/share/ltsp/server/dnsmasq/ltsp-dnsmasq.conf in /etc/dnsmasq.d/ltsp-dnsmasq.conf
Restarted dnsmasq
root@ltspserver:~# !36
**systemctl status dnsmasq**
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-10-04 11:58:07 -03; 13s ago
  Process: 3286 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
  Process: 3287 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 3295 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
 Main PID: 3294 (dnsmasq)
    Tasks: 1 (limit: 4915)
   Memory: 2.0M
   CGroup: /system.slice/dnsmasq.service
           └─3294 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-a

**sometimes show it shows:**
out 04 11:58:07 ltspserver dnsmasq-dhcp[3294]: DHCP, IP range 192.168.67.20 -- 192.168.67.250, lease time 12h
out 04 11:58:07 ltspserver dnsmasq-tftp[3294]: TFTP root is /srv/tftp
out 04 11:58:07 ltspserver dnsmasq[3294]: reading /etc/resolv.conf
**out 04 11:58:07 ltspserver dnsmasq[3294]: using nameserver 200.x.x.x#53
out 04 11:58:07 ltspserver dnsmasq[3294]: using nameserver 200.x.x.x#53**
out 04 11:58:07 ltspserver dnsmasq[3294]: read /etc/hosts - 5 addresses
out 04 11:58:07 ltspserver systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
out 04 11:58:08 ltspserver dnsmasq-dhcp[3294]: no address range available for DHCP request via enp5s0

But, if I reset server it does not show 

systemctl status dnsmasq
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-10-04 11:58:07 -03; 1h 27min ago
  Process: 3286 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
  Process: 3287 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 3295 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
 Main PID: 3294 (dnsmasq)
    Tasks: 1 (limit: 4915)
   Memory: 2.0M
   CGroup: /system.slice/dnsmasq.service
           └─3294 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-a

out 04 13:24:39 ltspserver dnsmasq-dhcp[3294]: no address range available for DHCP request via enp5s0
out 04 13:24:42 ltspserver dnsmasq-dhcp[3294]: no address range available for DHCP request via enp5s0

Same that it shows the DNS server the client no connect  on internet 

Other problem is with register user. The client side up and no ask for user and password and do logon with user ltspserver automatically

Thanks attention 

Douglas
@alkisg

**Comment by alkisg** [comment]
Hi Douglas,

to be honest, LTSP can't support every distribution out there, unless the distribution users send patches. And personally I'm only interested in big distributions, that have >100 active developers.

That said, if someone wants to join the [IRC channel](https://webchat.freenode.net/#ltsp?nick=ltsp_user?), we might be able to make it work with remote support (reverse VNC). But it's hard to troubleshoot distributions via issues/mails etc, a developer needs to have immediate access to it.

**Comment by alkisg** [comment]
So, after IRC/VNC, the fixes involved were:

- To stop autologin: PRE_INIT_FIX_TDM="sed '/^Auto/d' -i /etc/trinity/tdm/tdmrc"
- To enable NAT in ltsp.conf: NAT=1
- To add missing iptables for NAT: apt install iptables
