### ISSUE TITLE
TFTP and user management  issue

### ISSUE THREAD

**Issue by keerthi-varuman** [ltsp/ltsp#445]
**TFTP**
sometimes when I re-boot the LTSP Client I am getting **TFTP** time out.
what needed to be done for that....?

I have enabled all this in `/etc/dnsmasq.conf`

```
resolv-file=/etc/resolv.conf
enable-tftp
tftp-root=/srv/tftp
```  
**User management**
when I want to shutdown ltsp client I am getting a message `A stop job is running for User Manager for UID 1016 (1min 39 /2min)`
it is taking 2 min every time to shut down.
please guide me to fix those issues 

Thank you

**Comment by alkisg** [comment]
For the TFTP, what's the output of this command?
grep -r bind-interfaces /etc/dnsmasq*

For the shutdown process, which process is it? It doesn't sound related to LTSP.

**Comment by keerthi-varuman** [comment]
Here is the result of  grep -r bind-interfaces /etc/dnsmasq*

```
root@deepanam.av:~# grep -r bind-interfaces /etc/dnsmasq.conf 
#bind-interfaces
```

**Comment by alkisg** [comment]
Does the tftp timeout happen with all clients, or with just a specific one?
Can you take a photo of its screen when the problem happens?

**Comment by keerthi-varuman** [comment]
Getting TFTP error randomly on random clients, and when we start the server and client on next day all works fine I have no idea where could be the issue. 

Please check the attached image 

![tftp](https://user-images.githubusercontent.com/75841376/116071775-ebc35e80-a6ab-11eb-84f2-c20a28c240f6.jpg)
