### ISSUE TITLE
Authentication failed in Ubuntu 21.04

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#450]
Authentication fails while testing LTSP in Ubuntu MATE 21.04.
The same setup succeeds in Ubuntu MATE 20.10.

**Comment by alkisg** [comment]
Thanks, fix committed in d17c09b.

Ubuntu 21.04 includes sssd by default, to allow clients to join active directory.
But sssd.service only starts if /etc/sssd/sssd.conf exists, so it makes sense to do the same check in LTSP.

**Comment by alkisg** [comment]
I don't think it's worth it to release a new LTSP version just for that.
If anyone wants to try out LTSP in Ubuntu 21.04, they'll need these lines in ltsp.conf:

```
#Under [clients]
# Work around LTSP issue #388
PRE_INITRD_BOTTOM_RSYNC='chroot() { rw /bin/chroot "$@"; }'
# Work around LTSP issue #450
PAM_AUTH_TYPE=Primary
```

**Comment by fottsia** [comment]
Confirming that the workaround works for Ubuntu 21.10 as well.

**Comment by alkisg** [comment]
In commit 1db2233 the `rsync` call was replaced with `cp -au` so the workaround for 21.04/21.10 chroots isn't needed anymore.
