### ISSUE TITLE
I pushed an initial implementation and I uploaded a build in the LTSP proposed PPA.

### ISSUE THREAD

**Issue by Akshay-Hegde** [ltsp/ltsp#464]
I pushed an initial implementation and I uploaded a build in the LTSP proposed PPA.
Pamltsp now should support:

- The [aforementioned SSSD setup](https://wiki.ubuntu.com/Enterprise/Authentication/sssd)  (or similar LDAP setups). The administrator is supposed to configure the LTSP image or chroot to authenticate against LDAP, and pamltsp automatically handles the SSHFS mounting whenever that is needed (i.e. /home isn't already mounted via NFS).
- The usual SSH authentication for installations not using LDAP.
- Local accounts if /etc/shadow contains their password hashes.

There's no need to set any ltsp.conf variables, everything should be autodetected. Nevertheless, the following variables are respected:

- PAM_AUTH_TYPE="0|Primary|Additional": 0 means don't use pamltsp at all, e.g. for LDAP+NFS. "Primary" means do authentication with it, e.g. no LDAP. "Additional" means only do SSHFS with it, e.g. LDAP+SSHFS.
- SSH_SERVER="192.168.67.1": set a different SSH/SSHFS server than the boot server.
- SSH_OPTIONS="-p 8022": set a different SSH port or other SSH options.

I'll close this issue, but please test and report if I overlooked something.

_Originally posted by @alkisg in https://github.com/ltsp/ltsp/issues/338#issuecomment-735230997_

# Below are my conf

Server: Debian 10 
On my server I used `libnss-ldapd libpam-ldapd ldap-utils nscd ` and configured with LDAP successfully, I can login any LDAP users on my server however if I build image 

```
ltsp image /,,/boot,subdir=boot
ltsp kernel
ltsp initrd
```
I can't login on client machine, 

ltsp.conf
```
# awk 'NF && !/^#/' /etc/ltsp/ltsp.conf 
[server]
[common]
[clients]
PAM_AUTH_TYPE="Additional"
[61:6c:6b:69:73:67]
[b8:27:eb:*|dc:a6:32:*]
[administrator-pc]
[crt_monitor]
X_HORIZSYNC="28.0-87.0"
X_VERTREFRESH="43.0-87.0"
X_MODES='"1024x768" "800x600" "640x480"'
```

- Client to Server: `ssh anyldapuser@netboot-server` will work
- Firewall :  `LDAP server access is available only to netboot-server`

Please guide me how to fix this, my understanding is pamltsp will authenticate users using `SSH`, please correct me if I am wrong.

**Comment by alkisg** [comment]
Hi, please open a discussion instead of a bug report.

https://github.com/ltsp/discussions

**Comment by Akshay-Hegde** [comment]
Thanks followed sorry for the inconvenience.
