### ISSUE TITLE
AUTOLOGIN with IMAGE_TO_RAM=1 issue

### ISSUE THREAD

**Issue by HellishGyp** [ltsp/ltsp#484]
Hello! I have issue with using AUTOLOGIN and IMAGE_TO_RAM=1 in same time
I use Ubuntu 20.04.2 with GDM
VM server (4vCPU 8Gb RAM 20Gb HDD)
VM client (2vCPU 4Gb RAM 10Gb HDD)
UEFI boot 

config:
...
[clients]
[00:0c:29:e9:45:1b]
AUTOLOGIN="user"
RELOGIN=1
IMAGE_TO_RAM=1
HOSTNAME="DB01"
GDM3_CONF="WaylandEnable=false"
PASSWORDS_DB01="user/some_pass_in_base64"
...
in this case user doesnt automatically logging in after client boot
![image](https://user-images.githubusercontent.com/60817363/122537709-826a2700-d02e-11eb-8928-952de844e880.png)
 when i comment line IMAGE_TO_RAM=1 - it's work ok
![image](https://user-images.githubusercontent.com/60817363/122537904-b8a7a680-d02e-11eb-83a5-aab7f1fac2de.png)

**Comment by alkisg** [comment]
Hi, IMAGE_TO_RAM was implemented by this pull request: https://github.com/ltsp/ltsp/pull/86

For issues regarding IMAGE_TO_RAM, please file a pull request as well, as personally I'm not using it in any installations.
Please also verify that any PRs do not break the normal boot use case.

**Comment by alkisg** [comment]
A month has passed with no PR, closing, reopen if needed.
