### ISSUE TITLE
ValueError exception triggered in pwmerge

### ISSUE THREAD

**Issue by bbinet** [ltsp/ltsp#487]
See screenshot below:

![shrink_IMG_20210630_182348](https://user-images.githubusercontent.com/76281/123998913-3c1fab00-d9d2-11eb-9fe1-907ebb727e17.jpg)

Do you know what's wrong with the line `bruno:x:1000` ?

**Comment by alkisg** [comment]
Hi Bruno, please open a discussion issue for this one as it's not an LTSP bug, it's a bug in your /etc/group.

**Comment by bbinet** [comment]
=> https://github.com/ltsp/ltsp/discussions/489
