### ISSUE TITLE
ltsp ipxe: verify ipxe/memtest integrity

### ISSUE THREAD

**Issue by vagrantc** [ltsp/ltsp#49]
To verify the integrity of the downloaded ipxe binaries, it would be good to use something above-and-beyond https, such as a gpg-signed checksum file, to avoid man-in-the-middle attacks or a compromised download server sending malicious binaries.

**Comment by alkisg** [comment]
The server gets those files over "secure" https, while the clients get them from the server over tftp, which is much easier to compromise with man-in-the middle attacks.

Let's try filing bug reports first and see if we can get these files included in standard Debian packages. If this doesn't work out, then sure we can include the maintainers' public keys in the ltsp package and verify the downloaded file signatures.

**Comment by vagrantc** [comment]
> The server gets those files over "secure" https, while the clients get them from the server over tftp, which is much easier to compromise with man-in-the middle attacks.

But requires presence on the local network, so I still think it's worth providing additional protections where we can. Though iPXE *does* allow downloading kernel/initrd/etc via https, if we really wanted to go that route.

> Let's try filing bug reports first and see if we can get these files included in standard Debian packages. If this doesn't work out, then sure we can include the maintainers' public keys in the ltsp package and verify the downloaded file signatures.

I'll try to get the packages updated, but in the meantime will try to implement a signed checksums file that can be verified with "gpgv". Then we'll need to add some signing keys and store them somewhere, somehow, and/or use our personal gpg keys.

> I also want to wait a bit to see if ipxe won't work at all with a few NICs, and pxelinux or grub fallbacks or replacements are needed, which will affect the resolution of this issue... but of course as always, patches are welcomed!

Pretty sure we'll need something other than iPXE for armhf/armv7 and arm64/aarch64.

I'll work on a quick fix for this issue now and hopefully get the necessary package fixes in Debian, at least. Though if we want it to be cross-distro, it'd be nice to have a distro-independent source for the binaries.

FWIW, I'm less worried about memtest, as that seems a more optional feature, while the current infrastructure is highly dependent on iPXE.

**Comment by alkisg** [comment]
> Though if we want it to be cross-distro, it'd be nice to have a distro-independent source for the binaries.

We should also think about how to handle UEFI secure boot.

- The iPXE developer is trying to get it [signed by Microsoft](http://ipxe.org/appnote/etoken#uefi_secure_boot_signing_using_a_digicert_etoken), but he hasn't been able to yet (except for non publicly released variants). If he manages to do this, then that version should be preferred to unsigned distribution-compiled binaries.
- Ubuntu has [refused to sign ipxe.efi](https://bugs.launchpad.net/ubuntu/+source/ipxe/+bug/1811496/comments/7)
- After a few bugs are solved, shim might be able to get grubnet.efi loaded under secure boot. But while shim will be signed by Microsoft, it will only be able to load grubnet.efi and then kernels signed by the same distribution, not any distribution.

So some things are in favor of an distro-independent source, and some the exact opposite. Let's see what the future brings...

**Comment by vagrantc** [comment]
which exact files need to be added to the ipxe package in Debian?

In Debian, ipxe 1.0.0+git-20190125.36a4c85-1 includes the following files:

ipxe.efi  ipxe.iso  ipxe.lkrn  ipxe.pxe  undionly.kkpxe  undionly.kpxe

Do they need patches or other special build flags?

**Comment by alkisg** [comment]
I think snponly.efi and memtest.{0,efi} are missing. The basic one is just snponly.efi, which is what we're using by default for UEFI netbooting.

One might argue that "ipxe.efi" is enough; it's not; it's using the internal drivers but it's **not** using the SNP stack (PXE stack) of the UEFI, so it won't work at all with NICs outside the iPXE codebase. We want to default to snponly.efi and only fall back to ipxe.efi if snponly.efi fails.

**Comment by vagrantc** [comment]
One-line patch submitted to the Debian bug tracking system:

https://bugs.debian.org/944321

**Comment by alkisg** [comment]
After IRC discussion, we agreed to the following path:

- We create an ltsp-binaries package and host it in the PPA
- This contains /usr/share/ltsp/binaries/<ipxe files>
- The installation instructions ask the administrator to install it if using the PPA
- Wget in the code is replaced with cp.

This is a short term solution, until snponly.efi lands on Debian. The ltsp code will be modified to take this into account, and:

- Prefer /usr/share/ltsp/binaries/*
- Fallback to /usr/lib/ipxe/*
- If snponly.efi isn't found, fall back to ipxe.efi
- If no binaries are found at all, just warn and continue without them

So, until snponly.efi lands on Debian, one would be able to either just use the PPA, or use ltsp.deb from Debian and ltsp-binaries.deb from the PPA, or even just wget the binaries manually into tftp.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/63f903f394615383811b8a02d4c1f0157443afb6, thanks for all the help Vagrant, closing.
