### ISSUE TITLE
Virtual Box Client stopped with Debian 10 Gnome

### ISSUE THREAD

**Issue by AsmoKoskinen** [ltsp/ltsp#5]
I have LTSP 19.08 installed in Virtual Box (Ubuntu 18.04 Mate, Debian 10 Mate, Debian 10 LXDE). Virtual Box Client works with all of them. But not with Debian 10 Gnome. Here is screenshot from Virtual Box Client stopped with Debian 10 Gnome.

LTSP is 19.08-1 201908181341 ubuntu18.04.1

![VirtualBox_LTSP Client_19_08_2019_09_17_21](https://user-images.githubusercontent.com/28524781/63246157-add12e80-c26a-11e9-9614-282d93b971d2.png)

**Comment by alkisg** [comment]
Thank you Asmo, fixed in https://github.com/ltsp/ltsp/commit/8c2bb0560bcccc1d493294f45b40aee1b6c0a5d4
