### ISSUE TITLE
Fail to import VirtualBox vmdk image.

### ISSUE THREAD

**Issue by 16pxdesign** [ltsp/ltsp#525]
Following documentation can`t import image from virutal box. Have done CHROOTLESS / CHROOT however stuck on VM. 
Image i used is clean Ubuntu Desktop 20.04  same i used for server i run LTSP srver
```bash
root@udesktop:/srv/ltsp# ln -rs /home/bill/ubuntu.vmdk /srv/ltsp/ubuntunew.img
root@udesktop:/srv/ltsp# ltsp image ubuntunew
LTSP command failed: blkid -po export /srv/ltsp/ubuntunew.img
Aborting ltsp
I don't know how to mount /srv/ltsp/ubuntunew.img
```

**Comment by alkisg** [comment]
Hi, please open a discussion instead of a bug report:
https://github.com/ltsp/ltsp/discussions

**Comment by alkisg** [comment]
@16pxdesign, do open a discussion, I will answer there.

I only closed this because it's a question, not a bug in the LTSP code, and you filed it under the wrong place...
