### ISSUE TITLE
dnsmasq via infoblox and dhcp options

### ISSUE THREAD

**Issue by HappyRizi** [ltsp/ltsp#527]
Many thanks to people who involved in devolving the LTSP solution.
I have been using ltsp since 2009 without any problems.

Server: ubuntu 20.04.3 LTS with one ethernet.
LTSP: ltsp 21.01-1~ubuntu20.04.1

I upgraded our ltsp5 to ltsp20. The old version worked fin with external dhcp server (infoblox). But now the client does not receive any boot file from ltsp server on the new one.
There are no documentation regarding parameters which involving external dhcp server.

I am using the dhcp options as following:

```
dhcp-option=17	"/srv/tftp/ltsp"
dhcp-option=66	"ltsp server IP-address"
dhcp-option=67	"/ltsp/ltsp.ipxe"

Clients gets IP address from infoblox and nothing happend:
-------------------(client boot)----------------------
CLIENT MAC ADDR: 2C 27 D7 ZD 12 E7 GUID: 00A07B09 4676 E011 0000 2C27DZD12E7
CLIENT IP: 10.WWW.XXX.YYY MASK: 255.255.255.0 DHCP IP: 10.220.ZZZ.PPP
GATEWAY IP: 10.WWW.XXX.1
_
-------(Stops her and nothing happens)--------------------
---------------(on the ltsp server)-----------------------------------
journalctl -fu dnsmasq
sysuser@ltspserver:~$ journalctl -fu dnsmasq
-- Logs begin at Thu 2021-08-19 15:44:24 CEST. --
Sep 06 09:42:10 ltsp1 dnsmasq-dhcp[49095]: PXE(enp10s0) 00:24:81:e3:af:84 proxy
Sep 10 08:24:00 ltsp1 dnsmasq-tftp[49095]: error 0 TFTP Aborted received from 10.www.xxx.211
Sep 10 08:24:00 ltsp1 dnsmasq-tftp[49095]: failed sending /srv/tftp/ltsp/ltsp.ipxe to 10.www.xxx.211    
Sep 10 08:24:00 ltsp1 dnsmasq-tftp[49095]: sent /srv/tftp/ltsp/ltsp.ipxe to 10.www.xxx.211			
```
	
------------------------------------------------------------
I think there are something wrong with the infoblox parameters. Is there someone who tried this with infoblox and please let me know if my dhcp options 17, 66 and 67 are correct.
Thanks.

**Comment by alkisg** [comment]
Hi, please open a discussion instead of a bug report:
https://github.com/ltsp/ltsp/discussions
