### ISSUE TITLE
Default to OVERWRITE=1

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#53]
The `ltsp --overwrite` flag may be used in the following applets:

- `ltsp -o dnsmasq` generates /etc/dnsmasq.d/ltsp-dnsmasq.conf
- `ltsp -o ipxe` generates /srv/tftp/ltsp/ltsp.ipxe
- `ltsp -o  nfs` generates /etc/exports.d/ltsp-nfs.exports

All those files usually have autogenerated content; if users need to edit dnsmasq or nfs configuration, they may create additional files.

So it might be a good idea to default to OVERWRITE=1. Administrators that need to protect e.g. their ltsp.ipxe may specify OVERWRITE=0 in ltsp.conf.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/f789643b36f6a645c7add74f27955096cf6dc669.
