### ISSUE TITLE
Unable to change client hostname prefix

### ISSUE THREAD

**Issue by diegobenincasa** [ltsp/ltsp#57]
Hi all.

I've followed the instructions on how to set up **ltsp.conf** file ([here](https://ltsp.github.io/man/ltsp.conf/)) and have the **HOSTNAME_PREFIX** directive to prepend a user-defined text to client hostnames, but so far I didn't succeeded in having those names actually set.

Tried re-running `ltsp initrd`, `ltsp image /` (I'm in a chrootless environment), and all sort of ltsp commands. All of them to no avail.

If anyone can help, I appreciate. I don't really know if it's a bug or me not setting things up correctly.

**Comment by CharlesMAtkinson** [comment]
> But the question is, which ones are better, should I change the code or the documentation? :)

Against HOSTNAME_PREFIX and HOSTNAME_SUFFIX is that there should be something in the middle.

Against HOSTNAME_BASE and HOSTNAME_EXTRA is that they do not clearly reflect what the values are used for.

How about THIN_HOSTNAME_PART_1 and THIN_HOSTNAME_PART_2?

**Comment by alkisg** [comment]
Thank you guys, fix committed in https://github.com/ltsp/ltsp/commit/a3452b91ba5f03248a894d4368ebd8ec08559d04.

THIN_* names weren't very appropriate as currently LTSP is mostly about FAT clients. I decided to completely remove HOSTNAME_PREFIX and HOSTNAME_SUFFIX and only leave the HOSTNAME parameter, but with the following addition: now the %{IP} and %{MAC} pseudovariables are supported, so one can e.g. put this in ltsp.conf:

```shell
HOSTNAME="ltsp${IP}"
```

...which is the default HOSTNAME value in the new code.

I've initiated a [PPA build/upload](https://code.launchpad.net/~ltsp/+recipe/ltsp-proposed), it will be available in an hour or so, please update your ltsp.conf if you've been using HOSTNAME_PREFIX or HOSTNAME_SUFFIX.

**Comment by alkisg** [comment]
By mistake the previous build had a [debug_shell](https://github.com/ltsp/ltsp/commit/a3452b91ba5f03248a894d4368ebd8ec08559d04#diff-bc4655594c90f4787917d107bb18d833R97) enabled; I just sent another one that removed it. Sorry for that.
