### ISSUE TITLE
Client Autologin help

### ISSUE THREAD

**Issue by wolfclan68** [ltsp/ltsp#58]
I've been beating my head against the wall trying to get this to work. I've followed the example in the LTSP.conf MAN page exactly, but I cannot get my test client to autologin. Yes, I updated the image and ran initrd. What am I missing? Here is the excerpt from my ltsp.conf

```shell
[clients]
# Specify an /etc/fstab line for NFS home; note this is insecure
# FSTAB_NFS="server:/home /home nfs defaults,nolock 0 0"

# MAC address, IP address, or hostname sections can be used to apply settings
# to specific clients.
[00:1d:92:e5:b6:b3]
HOSTNAME=LTSP83
PASSWORDS_LTSP83="user83:Q0BsdmFyeTIwMTk="
AUTOLOGIN=1 
```

**Comment by alkisg** [comment]
Sorry this is a documentation issue. The correct separator there is slash (/), not semicolon (:).

Will fix it shortly.

**Comment by wolfclan68** [comment]
Thank you. I updated the conf and reran the image and initrd, but it still just comes to the user screen and wants me to click an account and type the password. It's as if it's just ignoring it. What should I do? Thanks for your assistance.

**Comment by alkisg** [comment]
Ah you also need AUTOLOGIN=user83, not 1.

**Comment by wolfclan68** [comment]
Thank you for your help, all fixed. I have another question but will start a separate topic.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/9acd9b6e46b0fd08e6ede33f487856c738fca66a.

The documentation in ltsp.conf was fine; but I had forgotten to update the example at the end of ltsp.conf. Thanks again.

**Comment by alkisg** [comment]
In https://github.com/ltsp/ltsp/commit/5eb9a97281c4726a76890aa810a35c833a5430ad I made RELOGIN work in LightDM, which wasn't working previously. The workaround was to set autologin-user-timeout=1; this causes a login "flickering"; I filed an [issue in lightdm](https://github.com/canonical/lightdm/issues/97) for that.

I also changed RELOGIN to default to 1 instead of 0 as it's usually what people that set AUTOLOGIN want.

**Comment by doguibnu** [comment]
Hello
I'm using Voyager, which is Ubuntu with XFCE and lightdm-gtk-greeter, and for me autologin-user-timeout=1 doesn't work and I need to set RELOGIN_TIMEOUT=2 in ltsp.conf to make it work"

Douglas

**Comment by alkisg** [comment]
Thank you Douglas, reopening; I'll test with lightdm-gtk-greeter and probably set timeout=2 so that it works in all greeters; hopefully lightdm will be fixed to support timeout=0 too.

**Comment by alkisg** [comment]
I tested with xubuntu-18.10-desktop-i386.iso.

autologin-user-timeout=1 worked fine in a fast VM client.
In a slow real client, autologin-user-timeout=2 was needed.

So I think that's a race condition in lightdm-gtk-greeter, someone should file a bug report there.

Fix committed in https://github.com/ltsp/ltsp/commit/59109f6830ce6f7b4cd3ecb22808a48e6044b14d.

**Comment by alkisg** [comment]
Btw for cases where autologin-user-timeout=2 isn't a good solution, there's also this:

https://github.com/spanezz/lightdm-autologin-greeter

**Comment by 88plug** [comment]
Final working config for me was :

[clients]

[00:1d:92:e5:b6:b3] 
HOSTNAME=ltsp34
AUTOLOGIN=janice
RELOGIN=1
PASSWORDS_LTSP34="janice/password"
```
Make sure your password is encoded with base64! ```echo password | base64```

**Comment by doguibnu** [comment]
The next week I will to try config again for clients auto login. Now after pandemic state the school lab go up! I hope can see ltsp working nice and the director school is happy after great job: get clients pcs, sever, mouses, keyboards, eletric plugs, screens, tests, install the switch, network cables, more test, internet fiber provider contract owwwwwww very pacient state. And my very best thanks for Mr. Alkis. Great Person for questions and answer, help a lot ever. Lets GO!

**Comment by bgpublic** [comment]
To anyone still struggling with auto login after reading everything above (like I was), please be sure to simply try RELOGIN=0, as was pointed-out in a similar thread is needed to work-around a bug in LightDM

**Comment by alkisg** [comment]
@JlnWntr read the documentation and ping if you don't undestand it.
From https://ltsp.org/man/ltsp.conf/#AUTOLOGIN:

> For example, AUTOLOGIN="pc/guest" means "automatically log in as guest01 in pc01, as guest02 in pc02 etc".

Also, it's best to open new discussions rather than comment in old issues.
