### ISSUE TITLE
Hostname on RPi client is always the first octet of the IP address

### ISSUE THREAD

**Issue by intelliant01** [ltsp/ltsp#582]
Hostname on Pi client is always the first octet of the IP address.
Server address is 192.168.2.97/24
Hostname is always 192.
Defining `HOSTNAME=ltsp%{IP}` explicitly in ltsp.conf fixes it to the expected ltsp+last octet of IP address e.g. ltsp115
This problem manifests only on Pis and not on x86 clients.

**Comment by intelliant01** [comment]
Updated ltsp from the proposed ppa.

When booting in rw mode into the chroot, the displayed hostname at the top of the login screen is **192**. Earlier this was 192.
Logged in as root and the requested contents are -

![IMG_20211019_074154](https://user-images.githubusercontent.com/2577060/137844476-fccd1188-882b-4753-9e0c-cc29db880148.jpg)

----
When booting in ltsp mode i.e. the image, the displayed hostname at the top of the login screen is the entire IP address - **192.168.2.105**. Earlier this was 192.
Logged in as a user teacher1 and the requested contents are -

![IMG_20211019_075753](https://user-images.githubusercontent.com/2577060/137844772-148687a1-f6a2-49f3-b41a-7e0921085460.jpg)

----
Added `HOSTNAME=mss%{IP}` to ltsp.conf which fixed the displayed hostname on login screen as well as the terminal prompt to **ms105**. This used to work earlier as well.
Logged in as user teacher1 and the requested contents are -

![IMG_20211019_084919](https://user-images.githubusercontent.com/2577060/137844964-41648e44-d80d-40a3-ba20-231be7a8b4e3.jpg)

**Comment by alkisg** [comment]
As you can see, the contents of that file mention that HOSTNAME=192.
This is NOT set by LTSP. It's sent by your DHCP server and it's set by initramfs-tools.
LTSP then just reads the HOSTNAME from that file.

What is the output of this command, as root on the client?

sudo /usr/lib/klibc/bin/ipconfig -n eth0

If it says hostname=192, then the issue is in your DHCP server configuration.
If it doesn't say hostname=192, then it would be a bug in initramfs-tools; possibly Ubuntu-specific as it doesn't happen in Raspberry Pi OS.

**Comment by intelliant01** [comment]
> When dnsmasq is used in proxy mode, ipconfig returns the hostname from the REAL dhcp server, e.g. the router.

So initramfs-tools seem consistent in their function in all these scenarios. Do you see `hostname :` when booting a Raspberry OS client in non-proxy mode?

> What are you using as the real dhcp server when you're testing the proxy dnsmasq mode?

dnsmasq from the gateway server of my network.

**Comment by alkisg** [comment]
The related change is this one: https://github.com/ltsp/ltsp/commit/d4a67e71b0d00b913c59abb470ff9df050e8cb81

If your DHCP server sends hostname=192.168.2.105, LTSP eventually runs `hostname 192.168.2.105`.
This means that your hostname is:

- full (hostname -f): 192.168.2.105
- short (hostname -s): 192
- domain (hostname -d): 168.2.105

So, lightdm displays your full hostname, including its "domain name" of 168.2.105. Everything is working as expected except for your main dnsmasq configuration (which also might be working as expected, if you've set some option to provide the IP as hostname; see what the dnsmasq list says about that).

**Comment by alkisg** [comment]
Ah, sorry I misunderstood then. Heh, it seems I can't reproduce any of the issues that you're reporting! Running dnsmasq in real DHCP mode, and `ipconfig -n eth0` from an rpi, doesn't cause the hostname=ip issue here.

Could it be related to the recent dnsmasq patches? Have you tried with the stock Ubuntu 20.04 dnsmasq?

**Comment by alkisg** [comment]
At my office I have an rpi2b, the one I tested with. At home I also have rpi3 and rpi4.
I might test Ubuntu MATE on rpi4 for 22.04, we'll see later on as I'm a bit busy currently.
