### ISSUE TITLE
Client template

### ISSUE THREAD

**Issue by wolfclan68** [ltsp/ltsp#59]
Does anyone know a way to create a clone of a user account? I've Googled for it, but what I've found doesn't do it quite right. I plan to deploy workstations, the same hardware just replacing Windows 7, to various classrooms and would like them to be identical. In Active Directory with Windows, they could all be signed into the same account, but that doesn't work with LTSP. Thank you for any assistance.

NVM I Googled a little more and found this script that works quite nicely https://unix.stackexchange.com/questions/204970/clone-linux-user-copy-user-based-on-another-one

**Comment by enaut** [comment]
This sounds to me that you don't want a clone of a user but actually you want a guest user - no persistent files everything is reset after every login - else you will end up with a lot of lingering files and browser password store will be a security nightmare. So look at guest users discussed here: https://github.com/ltsp/community/issues/14
If you are done with the issue close it.
