### ISSUE TITLE
Admin Account Merged with Client and Admin no longer available

### ISSUE THREAD

**Issue by RaulBustamante** [ltsp/ltsp#601]
I modified the name for my login user (Team1) to my name for testing purposes to "myname" I was logged in the server pc with my new user name "myname" and I also  logged in a different pc as a client with the same user name. (which has admin rights) 

I changed the background in the client pc, logged out, then logged out of the admin pc and when I logged back in to the admin pc and see if the change was reflected.

Even though I logged in as the admin, LTSP is no longer recognized by client pc's and It seemed to merge the admin as a regular group member.

Still not exactly sure what happened.

Thanks. 

If it's a question or discussion that will probably not result in LTSP code or documentation changes, please start a discussion instead:
https://github.com/ltsp/ltsp/discussions

**Comment by alkisg** [comment]
Hi @RaulBustamante, as this is not a problem with the LTSP code, please open a discussion instead of a bug report, by going to https://github.com/ltsp/ltsp/discussions and clicking the "New" button.
