### ISSUE TITLE
Enable NAT=1 does not fix internet client connection (2 NICS)

### ISSUE THREAD

**Issue by doguibnu** [ltsp/ltsp#61]
Hello!
How are you

I Enable NAT=1 in ltsp.conf but does not fix the internet connection at client side. Still need the command: systemctl restart ltsp
for client can navigate 

Thanks

**Comment by alkisg** [comment]
Hi Douglas,

there was a problem in the latest Debian packaging, which made the LTSP service not start, and it was fixed a week ago, so you just needed to update to the latest LTSP version.

Thanks, closing the issue.
