### ISSUE TITLE
Missing required packages in installation documentation.

### ISSUE THREAD

**Issue by jmgibson1981** [ltsp/ltsp#617]
I noticed this awhile back and never bothered to figure it out due to lack of time back then. Following the directions I noticed that I had a consistent failure to login. I tracked this down to the /home directories. Changing to NFS solved the issue. I recently started messing about with it again. All one needs is the sshfs package in the client image (either host or chroot method). I couldn't find it as a dependency on any of the packages listed for base installation @https://ltsp.org/docs/installation/ Just an update to that page might be in order?

**Comment by alkisg** [comment]
Please read the following paragraph of that page, more closely:

> In the virtual machine and chroot cases, you're supposed to install the ltsp package to the image, by adding the LTSP PPA and running `apt install --install-recommends ltsp epoptes-client`, without specifying any other services.

The ltsp package recommends the sshfs package, so it gets installed as well.

**Comment by jmgibson1981** [comment]
My apologies. Thank you for the clarification.
