### ISSUE TITLE
How has ltsp broken ssh?

### ISSUE THREAD

**Issue by danboid** [ltsp/ltsp#630]
Earlier today I installed the recommended LTSP server packages from the LTSP PPA under Ubuntu server 20.04:

```
apt install --install-recommends ltsp ltsp-binaries dnsmasq nfs-kernel-server openssh-server squashfs-tools ethtool net-tools epoptes
```

and I also ran the recommended LTSP commands:

```
ltsp dnsmasq
ltsp image Ubuntu20.04
ltsp ipxe
ltsp nfs
ltsp initrd
```
After running those commands, I can no longer ssh into my server so my first suspicion is that that is most likely the fault of `ltsp dnsmasq`. I suspect it is making some assumptions about my network config that are not correct although I've not confirmed that yet.

The main connection on my LTSP server and the one that I'd want dnsmasq to be using is a bond, bond0 which comprises of 4x gigabit ethernet connections and its address is of the form  146.87.X.X. Could the fact that this is a bonded connection and/or that its using a non-standard IP address be causing issues for `ltsp dnsmasq`? I have configured the interfaces using netplan.

This server also has another 10 Gb fibre connection to our old LTSP server. I wouldn't want dnsmasq to use this link and it has a 192.168.x.x address.

We are going to be using an external DHCP server with this new LTSP server, as we are currently with the existing LTSP5 server. I've not looked at the code for `ltsp nfs` yet but I can't imagine that would break ssh.

**Comment by alkisg** [comment]
Hi Dan, I don't think `ltsp dnsmasq` or ltsp in general is related to this issue. It's possible that one of the other commands that you ran, like `sudo systemctl mask systemd-networkd-wait-online.service` (that you mentioned on IRC), is to blame.

**Comment by danboid** [comment]
I was looking at this in 55-dnsmasq.sh:

```
proxy_dhcp() {
    local cidr _dummy subnet netmask separator

    ip route show | while read -r cidr _dummy; do
        subnet=${cidr%%/*}
        case "$subnet" in
            127.0.0.1|169.254.0.0|192.168.67.0|*[!0-9.]*)
                continue
                ;;
            *)  # Ignore single IP routes, like vbox NAT gateway
                test "$cidr" != "${cidr#*/}" || continue
                netmask=$(length_to_netmask "${cidr#*/}")
                # echo in dash translates "\n", use printf to keep it
                printf "%sdhcp-range=set:proxy,%s,proxy,%s" \
                    "${separator}" "$subnet" "$netmask"
                # Insert a separator only after the first line
                separator="\n"
                ;;
        esac
    done
}
```

Esp the lines

case "$subnet" in
            127.0.0.1|169.254.0.0|192.168.67.0|*[!0-9.]*)

That wouldn't work for the 146.87.*.* address given to the bond0 interface that I want run dnsmasq on. Would it not matter?

**Comment by alkisg** [comment]
1) It works as expected for 146.x 
2) It wouldn't matter if it didn't work
3) Even if dnsmasq.conf was completely broken, it wouldn't block ssh

**Comment by danboid** [comment]
It does look like my dnsmasq config is at fauklt here because I disabled the dnsmasq service, rebooted and ssh id OK again.

What do you mean "it wouldn't matter if it didn't work". Surely I NEED dnsmasq to be running and configured correctly to run an LTSP server?

**Comment by danboid** [comment]
How would `ltsp dnsmasq` know which of my two interfaces to bind itself to? I'll have to edit its config to tell it to use bond0, surely?

**Comment by danboid** [comment]
I'll update the ltsp image man page tonight, will send a PR soon.

**Comment by danboid** [comment]
Actually, disabling dnsmasq hasn't been enough to stop ssh from stopping working after a while.

I only disabled systemd-networkd-wait-online.service after I started haviong these network issues, which have only started to happen since installing the LTSP server packages. I was using it fine for weeks before this.

**Comment by danboid** [comment]
I'm right in thinking I'll have to manually edit the dnsmasq config file to bind it to bond0 right?

Won't running it on my 192.168 network potentially cause probs? I don't want the hosts on that network to boot off LTSP.

**Comment by alkisg** [comment]
> What do you mean "it wouldn't matter if it didn't work".

I mean it wouldn't be the one to blame for the ssh issue that you reported. Of course you do need dnsmasq (or something similar) for ltsp.

> I'm right in thinking I'll have to manually edit the dnsmasq config file to bind it to bond0 right?

ltsp dnsmasq, with or without -p0, -r0 etc, can be used to do real dhcp on 192.168.67.x, and proxy dhcp on other subnets, e.g. 146.x.
It doesn't need to bind to any interface to do that.

If you want e.g. to do proxy in only one interface, and not others, you can create  an /etc/dnsmasq.d/local.conf and put an `interface` option there (see man dnsmasq).

**Comment by danboid** [comment]
Now I remember!

I knew I'd seen this shitty behaviour before. I'm pretty sure I know whats caused this so I think its fixed now.

The installation page recommends installing epoptes for an LTSP server. If you're like me and you've installed Ubuntu Server, you probably don't have X (and gdm3) installed so installing epoptes installs a minimal X config + gdm3 so after instyalling epoptes my server started booting to gdm3 instead of a text console login screen.

There seems to be a bug with Dell servers, Ubuntu 20.04 and gdm that causes it and ssh and other things to stop resonding after a while so the solution is to either mask the gdm3 service or switch to lightdm if you want a gui login screen.
