### ISSUE TITLE
New man pages not available in older distributions

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#635]
Regarding #634, on Ubuntu 16.04 I installed LTSP from the proposed PPA and `man ltsp.conf` showed:

```shell
open : no such file or directory
```

**Comment by alkisg** [comment]
Thanks, indeed older go-md2man versions have multiple problems.
I updated debian/control to prefer pandoc there; please test once more.

**Comment by fottsia** [comment]
Tested on Ubuntu 16.04, Ubuntu 18.04 and Debian 8 Jessie; it works fine, closing.
