### ISSUE TITLE
Extra mounts

### ISSUE THREAD

**Issue by Tuharsky** [ltsp/ltsp#637]
Hallo,
there has been discussion about ways to mount more directories from the server, not only user's home. It seemed to me that Extra Mounts function, as known with LTSP5, would be the most secure and elegant solution, and that it might be implemented in the future.
Is there please any update or useful hint?

**Comment by alkisg** [comment]
Mounting shared system directories using private user accounts is not not elegant. Example:

- User1 logs in on ltsp-client1
- Directory /srv is mounted using the User1 permissions
- User2 logs in on ltsp-client1 simultaneously, either using a terminal (`su - user2`) or with MULTISEAT=1
- Problem 1: when User2 reads from /srv, the permissions of User1 will be used (i.e. security chaos)
- Problem 2: when User2 writes to /srv, the files will be created with User1 as the owner
- Then suppose that User1 logs out (or even that account gets deleted by the sysadmin) while User2 is still connected
- Problem 3: what should happen with the mount and the files in use?

For user SSHFS mounts under /home/username, an /etc/xdg/autostart shell script can be used that will do:

```shell
# This just sets up passwordless ssh
/usr/sbin/ltsp remoteapps true
mkdir -p sshfs
sshfs server:/extramount sshfs
```

For system SSHFS mounts a separate server account should be set up, e.g. ltsp-share1. All users should have read-only access to the private SSH key of ltsp-share1. It should be fetched on LTSP client login over the secure SSH channel. And it should be used to permanently mount that directory on the LTSP client until it's powered off.

Personally I'm not interested in implementing this; so a pull request or funding will be needed. I'll tag the issue as "pr-or-fund" and leave it open for a while, then close it if it remains inactive. Thank you for the report.

**Comment by Tuharsky** [comment]
Thank You, Alkis.

**Comment by Tuharsky** [comment]
For the record and possibly to help others, I got it running this way.

1, I have created a file /etc/xdg/autostart/mount-user-dirs.desktop
```
[Desktop Entry]
Name=Mount folders
GenericName=Mount script
Comment=The script mounts folders from server
Exec=/etc/mount-user-dirs.sh
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
NoDisplay=true
```

2, The script file /etc/mount-user-dirs.sh
```
#!/bin/bash
# Test whether this is server login or client login (replace "server" with the actual server's hostname
machine_name=`hostname`
if [ "$machine_name" != "server" ]
    then
	/usr/sbin/ltsp remoteapps true
	# Creating mount point
	mkdir -p ~/data_disk
	# Mounting
	sshfs 10.1.1.1:/mnt/data_disk ~/data_disk
    fi
```
3, Made the script executabe by
chmod a+rx /etc/mount-user-dirs.sh

4, Regenerated the image

**Comment by felinira** [comment]
> ```
> #!/bin/bash
> # Test whether this is server login or client login (replace "server" with the actual server's hostname
> machine_name=`hostname`
> if [ "$machine_name" != "server" ]
>     then
> 	/usr/sbin/ltsp remoteapps true
> 	# Creating mount point
> 	mkdir -p ~/data_disk
> 	# Mounting
> 	sshfs 10.1.1.1:/mnt/data_disk ~/data_disk
>     fi
> ```

I tried this but it still asks for my password when running the script. Do I need to set something up here?
