### ISSUE TITLE
New man pages have –option instead of --option

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#640]
With the latest LTSP version from the PPA, `man ltsp` shows for example:

       -b, –base-dir=/srv/ltsp

Instead of:

       -b, --base-dir=/srv/ltsp

**Comment by alkisg** [comment]
Thank you, that was a pandoc issue, I reported it [there](https://github.com/jgm/pandoc/issues/5384#issuecomment-1013509940) and I used a workaround in our Makefile.
