### ISSUE TITLE
pamltsp problems and fixes

### ISSUE THREAD

**Issue by danboid** [ltsp/ltsp#646]
I had to make a few changes to pamltsp to get it working with LDAP / nslcd so I'll describe what I changed and then I'll let @alkisg decide how best to integrate these changes.

The first issue relates to the code pamltsp uses to detect local users. Because the user name that I have been using to test LDAP/LTSP logins with also exists in the LTSP image, pamltsp would always detect my user as being local ie remote=0 so I just removed these lines to ensure remote was always set to 1:

Detect if the user is local or remote
    if grep -q "^$PAM_USER:" /etc/passwd; then
        remote=0

In our case, we would only ever want allow remote logins. The only time we will use local logins is when I'm debugging LTSP as root but maybe other LTSP users do require local accounts? I'm not sure how to fix this for all use cases. Maybe it could go off the UID values, local users would usually be in early 1000s?

The next issue is that pamltsp was failing to create the home dir because $MKHOMEDIR never gets defined so I just had to change

```
if [ ! -d "$pw_dir" ] && [ "$MKHOMEDIR" != 0 ]; then
```

to

```
if [ ! -d "$pw_dir" ]; then
```

Note that I am going to be using pam_exec to create a ZFS dataset for users who don't already have a home dir. pam_mkhomedir.so doesn't support ZFS yet.

The final modification I made was to change:

```
sshfs -o "$sshfs_params" "$@" "$pw_name@$SSH_SERVER:" "$pw_dir" 2>&1); then
```

to

```
sshfs -o "$sshfs_params" "$@" "$pw_name@$SSH_SERVER:$pw_dir" "$pw_dir" 2>&1); then
```

**Comment by alkisg** [comment]
Hi Dan, the code you mention is fine, the only problem was that you didn't use PWMERGE_SUR to declare that you didn't want to pull in your local user but you wanted to use the same user account from LDAP instead. I.e. no ltsp code changes were necessary, you just needed an ltsp.conf directive.
