### ISSUE TITLE
sshd_config - how to change from port 22

### ISSUE THREAD

**Issue by hughdcampbell** [ltsp/ltsp#66]
I followed the recipe on the main page to install LTSP 19+ and it just worked(!) First time! Amazing! As a 10+ year user of LTSP, I expect to have to do _lots_ of trouble shooting - there is always some issue. So tremendous work, congratulations and thank you.

While it very clearly worked immediately (I got my remote client to the gdm login), I couldn't log in remotely. Instead, I got a "read: Connection reset" each time.

After a lot of fiddling, it turns out my sshd_conf on the server was set to a non-standard port (ie NOT port 22). I reset it to 22 in my sshd_conf, and everything works. 

Is there any way to reconfigure the sshd port? I can't spot where I might change this other than in the sshd_conf file.

It is not a complaint or a problem - I am really just mentioning it here in case it might help someone else who runs into the "read: Connection reset" issue.

**Comment by alkisg** [comment]
I'm transferring this to "bugs" (ltsp issues). I'll implement it as SSH_OPTIONS or something.

**Comment by alkisg** [comment]
I'm thinking that pamltsp should be rewritten as an LTSP applet after all... this will make it much easier to pass options from ltsp.conf to it. Will do, but a bit later than planned.

**Comment by alkisg** [comment]
I implemented this in https://github.com/ltsp/ltsp/issues/338#issuecomment-735230997, please test and report if I overlooked something.

**Comment by fottsia** [comment]
It appears to work fine here, thanks.
