### ISSUE TITLE
Support Raspberry Pis

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#68]
**Edit:**
**It's now possible to use LTSP to netboot Raspberry Pis with Raspbian.**
**Documentation at: https://ltsp.org/docs/installation/raspbian/**

***

In the future, Raspberry Pis might have nice embedded netbooting code that LTSP will be able to support. Currently though most of them need the kernel and initrd to reside locally in the SD card in order to boot as LTSP clients.

In LTSP5, generating a chroot was recommended for Raspberries. But the Raspbian image is a lot more optimized, so LTSP19 should have either code or documentation to download the image and transform it to either a chroot or a VM.

After that transformation, there are 3 ways to maintaining the Raspbian image:

- By installing qemu-user-static and using the `chroot` command on the server
- By installing qemu-user-static and using the `qemu` command on the server to boot the chroot or image as a VM
- By netbooting a Raspberry Pi with a special NFS read-write mode (*not* as LTSP client), so that any programs that are installed or any changes done are written directly to the server image.

The two first methods involve qemu processor emulation, which isn't very stable yet; so the third one should probably be the default.

And a small script or how-to will also be needed, to generate the LTSP client SD cards and the special NFS client SD card. Those cards will only contain the boot partition which is around 50 MB.

Due to lack of interest in Raspberry Pis, personally I won't be implementing this in the near future. But if someone wants to sponsor its development, or if someone is willing to become the "official LTSP Raspberry Pi tester, documentation maintainer and user supporter", which involves maintaining wiki pages and answering related community issues, then I'm willing to do this.

**Comment by alkisg** [comment]
Some starting points for netbooting raspberries:

- Name one of your RPIs SD cards the "administrative RPI SD card".
- Install Raspbian Buster there normally. Point to existing documentation for this, we don't want to maintain duplicate documentation.
- Run `update-initramfs -c -k $(uname -r)` to generate an initrd, as Raspbian by default doesn't use one, and it's needed for netbooting.
- Copy all the SD card contents to /srv/ltsp/raspbian with cp -a.
- Put this in the server /etc/exports.d/local.conf: `/srv/ltsp/raspbian       *(rw,async,crossmnt,no_subtree_check,no_root_squash,insecure)`
- Run `sudo exportfs -ra`
- Modify /srv/ltsp/raspbian/etc/fstab: `/dev/mmcblk0p1  /boot           vfat    defaults          0       2`

Then on the administrative RPI SD card, modify the following files:

- /boot/cmdline.txt: `console=serial0,115200 console=tty1 root=/dev/nfs nfsroot=192.168.67.1:/srv/ltsp/buster-raspbian elevator=deadline plymouth.enable=0 rw`
- /boot/config.txt: add: `initramfs initrd.img`

These steps should allow you to netboot the administrative RPI in NFS rw mode, so that any programs you install etc, go directly to the server. Once you've done and documented those parts, I'll write a script that creates the RPI SD cards.

**Comment by quiescer** [comment]
Would this allow Rasperry Pis as thin clients? I noted that the new LTSP version no longer supports thin clients, but our environment is based on a single server and multiple older PCs that have no disks and limited RAM, so we need to keep using thin clients.

**Comment by alkisg** [comment]
Hi, see this issue regarding thin client support:
https://github.com/ltsp/community/issues/32

In short, thin client support just needs someone to try it and document it in a wiki page.

If you want to try such a setup, with LTSP19 and e.g. xrdp on the server and lightdm-remote-session-freerdp2 for the clients, let's continue there, or start a new community issue, as it's not specific to Raspberries.

**Comment by jphein** [comment]
https://github.com/ipxe/pipxe is that what would be used to PXE boot them?

**Comment by alkisg** [comment]
Hey, this looks awesome. Will try it soonish.

**Comment by alkisg** [comment]
Hmm it doesn't work on rpi2 and rpi4 currently; I think it's only for rpi3 for now, and will support rpi4 in the future.

I'll test it with rpi3 tomorrow.

**Comment by alkisg** [comment]
My raspbian-buster kernel8.img showed a black screen with that, so I filed https://github.com/ipxe/pipxe/issues/1;
mcb30 said [this patch of his](https://github.com/raspberrypi/linux/pull/3252) is needed; will try with a newer kernel tomorrow.

Also TFTP was very slow for some reason; will try HTTP too.

**Comment by alkisg** [comment]
Results:

- Switching from TFTP to HTTP made the kernel/initrd load in 3 seconds instead of 3 minutes. We definitely want to support HTTP in LTSP.
- Booting with a newer kernel from https://github.com/Hexxeh/rpi-firmware was successful, although I think the blue/red colors were inverted.
- Debian's initramfs-tools has a problem where it runs `ipconfig` too fast, before udev has made the NIC available, so it exits with "No devices to configure". Adding "break=premount" in cmdline, waiting for 5 secs, and exiting the shell, works around that issue. We may also work around that from the LTSP code.

So with the next rpi kernel update, rpi3 should be very easily bootable with the new LTSP. I don't think we need any changes at all in the LTSP code, just a small wiki page that documents how to prepare the chroot and the pipxe sdcard. But I'll keep this issue open until then.

**Comment by alkisg** [comment]
This is the script that mcb30 uses to bypass the "device not available yet" issue:

```shell
#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

if [ -n "${BOOTIF}" ]; then

    # Get boot NIC MAC address (excluding separators)
    bootif_mac=${BOOTIF#*-}
    bootif_mac=${bootif_mac//-/}

    # Wait for matching NIC to appear
    delay=${ROOTDELAY:-180}
    count=0
    while [ ${count} -lt "${delay}" ] ; do
	[ "$quiet" != "y" ] && log_begin_msg "Waiting for boot NIC"
	for device in /sys/class/net/* ; do
	    if [ -f "${device}/address" ]; then
		test_mac=$(cat "${device}/address")
		test_mac=${test_mac//:/}
		if [ "${test_mac}" = "${bootif_mac}" ]; then
		    break 2
		fi
	    fi
	done
	sleep 1
	count=$((count + 1))
	[ "$quiet" != "y" ] && log_end_msg
    done
fi
```

**Comment by alkisg** [comment]
The tianocore UEFI implementation for rpi3 allows for stretching other resolutions to native.
This then made my 1600x900 screen boot in emulated 1920x1080.
To disable screen stretching, this needed to be done once:

Esc to enter UEFI setup → Device Manager → Raspberry Pi Configuration → Display → Uncheck all Virtual resolutions and leave only Native resolution.

This changes were then saved permanently, but I've no idea where, in some NVRAM or in the PIPXE SD card.

**Comment by jphein** [comment]
So excited to try this!

**Comment by gbaman** [comment]
@alkisg having taken a look at pipxe, is there a whole lot of benefit with this over using the built in network booking capability of the Pi 3B/3B+/4B (and using the bootcode.bin method for older Pis)?

It allows for leaving SD cards out completely (for more recent Pis) and handing the boot files over tftp directly.

I had LTSP5 (via PiNet) booting with SD card-less booting using this method fine. Now I am taking another stab at moving PiNet over to the newer LTSP, was my intention to go down that route so keep things simple for the user.

**Comment by alkisg** [comment]
Hi Andrew,

pipxe allows booting rpi clients without adding any pi-specific code to LTSP at all. Additionally, they're able to use the iPXE menu which supports multiple images, DEFAULT_IMAGE, MENU_TIMEOUT, KERNEL_PARAMETERS etc. So we'll be supporting that because we don't need any code in LTSP for it.

On the other hand, we also want to support the bootcode.bin method for older or sd-card-less rpi clients. This part just lacks patches or funding.

Finally, if someone needs my older KERNEL_DEVICE implementation that used a local kernel, we could support that too.

**Comment by seancarte** [comment]
(Sorry, I didn't find this thread when I searched initially.)

I have a RPi 3 b+ board that I want to use as a thin client, and I have an existing LTSP5 server.

I followed this documentation: https://help.ubuntu.com/community/UbuntuLTSP/RaspberryPi to add the required image to an existing LTSP5 server, but ran into two problems:
the LTSP build ended in errors, and
the RPi still seems to want to boot from the SD card; it doesn't attempt to use the network.

I am about to start from scratch with a new server. Has anybody got any advice on how to proceed? Would I be better off using the latest LTSP, or should I continue with LTSP5 on Ubuntu 16.04?

From the above, it looks like https://github.com/ipxe/pipxe would be worth investigating?

**Comment by alkisg** [comment]
Hello,

by following the steps I wrote in this topic, one can netboot an rpi3 using pipxe and the new LTSP. The problem though is that the colors are bad; we're waiting for an rpi kernel or tianocore update that will fix that.

The UbuntuLTSP page that I wrote for Ubuntu 16.04 might still work. For LTSP5 questions though, the appropriate place is the sourceforge mailing list.

Some people expressed interest in partially funding further development; maybe if others contributed too, it'd proceed quickly.

**Comment by seancarte** [comment]
Thanks, @alkisg , this has given me a starting point.

**Comment by alkisg** [comment]
A kind sponsor was found to partially fund Raspberry Pi LTSP support. My progress so far:

- I abandoned my pipxe tests, as it's not yet ready. It needs a kernel outside the standard repositories, and even then the colors are wrong, so at least 2 kernel fixes are needed before it becomes usable. Additionally, its TFTP implementation is extremely slow, so it would require a tiny HTTP server running on the LTSP server. Of course when those are fixed, LTSP will work fine with pipxe, no additional code will be needed.
- I managed to netboot rpi2 with just bootcode.bin in the SD card, which means that there's no need to support "local kernels" anymore.
- I also managed to netboot rpi3 without an SD card at all.
- I managed to netboot a clent in "nfs-rw mode" without an initramfs. This means that we can use that to maintain the "chroot", there's no need for qemu.
- Unfortunately bootcode.bin doesn't support multiple initrds. I reported that in https://github.com/raspberrypi/firmware/issues/1318. So, I'll modify `ltsp initrd` to created a merged ltsp.img just for Raspberries.
- Unfortunately Raspberries do not support organized TFTP subdirectories, they need everything in TFTP root. I reported that in https://github.com/raspberrypi/firmware/issues/1101. This means that we'd better use symlinks from the TFTP root to the raspbian/boot/* files.

So in the following days I'll develop an `ltsp raspberry` applet, that would help in unzipping the raspbian.img.xz, fixing a few things on the generated chroot, and doing all those symlinks.

**Comment by seancarte** [comment]
@alkisg , that is great news; thank you to the kind sponsor!

**Comment by alkisg** [comment]
Complete success, with LTSP 20.01 I was able to boot rpi2, rpi3b+ and rpi4 as LTSP clients.
No initramfs was used, the boot sequence was:

- either no sdcard for 3B+ and 4, or sdcard with just bootcode.bin,
- which loads the boot files from TFTP,
- then nfsroot is used to connect to the server's /srv/ltsp/raspbian,
- which then loads overlayfs and squashfs and chains to /srv/ltsp/images/raspbian.img
- ltsp.img is fetched via NFS right after that

I.e. NFS chroot is used in the place of an initramfs; then root is switched to the squashfs image for speed.

Unfortunately the funding was for 20 hours of work and I've already needed more than 80, so automating the final bits and documenting everything will have to wait; in the mean time, I'm available to set this up over VNC if someone needs it; if so, mail me.

I'll leave this issue open until everything gets committed upstream in LTSP.

**Comment by alkisg** [comment]
I uploaded preliminary documentation at https://ltsp.org/docs/installation/raspbian/

**Comment by seancarte** [comment]
Thanks, @alkisg . I had a go at following the documentation, but was not successful.

I needed to add 'norecovery' to mount /dev/loop8p2 read-only:
```

root@ltsp:~# mount -o ro /dev/loop8p2 /mnt
mount: /mnt: cannot mount /dev/loop8p2 read-only.
root@ltsp:~# mount -o ro,norecovery /dev/loop8p2 /mnt
```

This is normal, right?:
```

root@ltsp:/srv/ltsp/raspbian# ltsp kernel raspbian
Running: mount --bind --make-private -o ro /srv/ltsp/raspbian /tmp/tmp.LTXerhcPzw/ltsp/
Could not locate vmlinuz and initrd.img in raspbian
```

But this doesn't look good:

```
root@ltsp:/srv/ltsp/raspbian# exportfs -ra
exportfs: No options for /srv/ltsp/raspbian/*(rw,async,crossmnt,no_subtree_check,no_root_squash,insecure) : suggest (sync) to avoid warning
exportfs: /etc/exports.d/ltsp-raspbian.exports [1]: Neither 'subtree_check' or 'no_subtree_check' specified for export ":/srv/ltsp/raspbian/*(rw,async,crossmnt,no_subtree_check,no_root_squash,insecure)".
  Assuming default behaviour ('no_subtree_check').
  NOTE: this default has changed since nfs-utils version 1.0.x

exportfs: Failed to stat /srv/ltsp/raspbian/*(rw,async,crossmnt,no_subtree_check,no_root_squash,insecure): No such file or directory
```


I'm confused here. What is meant by 'boot a single client'? Off the SD card?

    Now boot a single client, add the LTSP PPA to your sources, and install only the ltsp package:
    apt install --install-recommends ltsp

**Comment by alkisg** [comment]
Hi seancarte,

> I needed to add 'norecovery' to mount /dev/loop8p2 read-only:

It is normal if your SD card wasn't unmounted properly and needs fsck.

> Could not locate vmlinuz and initrd.img in raspbian

You didn't do the RPI_IMAGE in ltsp.conf step.

> exportfs: Failed to stat /srv/ltsp/raspbian/*(rw,async,crossmnt,no_subtree_check,no_root_squash,insecure): No such file or directory

Put a space before "*".

> I'm confused here. What is meant by 'boot a single client'? Off the SD card?

No, over the network, at that point you should be able to netboot a single client, in NFS_RW mode, but not in LTSP mode.

**Comment by seancarte** [comment]
```
# grep ^[^#] /etc/ltsp/ltsp.conf 
[server]
RPI_IMAGE="raspbian"
[common]
MASK_SYSTEM_SERVICES="squid timedatectl"
[clients]
[crt_monitor]
X_HORIZSYNC="28.0-87.0"
X_VERTREFRESH="43.0-87.0"
X_MODES='"1024x768" "800x600" "640x480"'
```

I also added 
RPI_IMAGE="raspbian"
to the [server] section in /usr/share/ltsp/common/ltsp/ltsp.conf

but still:
```
root@ltsp:~# ltsp kernel raspbian
Running: mount --bind --make-private -o ro /srv/ltsp/raspbian /tmp/tmp.evJGGHjf2p/ltsp/
Could not locate vmlinuz and initrd.img in raspbian
```
I am able to boot a PC using the x86_64 image.
```
root@ltsp:~# ls /srv/tftp/ltsp/x86_64/
initrd.img  vmlinuz
root@ltsp:~# ls /srv/ltsp/raspbian/boot/
bcm2708-rpi-b.dtb         bcm2711-rpi-4-b.dtb  fixup.dat         start4cd.elf
bcm2708-rpi-b-plus.dtb    bootcode.bin         fixup_db.dat      start4db.elf
bcm2708-rpi-cm.dtb        cmdline.txt          fixup_x.dat       start4.elf
bcm2708-rpi-zero.dtb      config.txt           issue.txt         start4x.elf
bcm2708-rpi-zero-w.dtb    COPYING.linux        kernel7.img       start_cd.elf
bcm2709-rpi-2-b.dtb       fixup4cd.dat         kernel7l.img      start_db.elf
bcm2710-rpi-2-b.dtb       fixup4.dat           kernel8.img       start.elf
bcm2710-rpi-3-b.dtb       fixup4db.dat         kernel.img        start_x.elf
bcm2710-rpi-3-b-plus.dtb  fixup4x.dat          LICENCE.broadcom
bcm2710-rpi-cm3.dtb       fixup_cd.dat         overlays
root@ltsp:~# ls /srv/tftp/
ltsp
root@ltsp:~# ls /srv/tftp/ltsp/
ltsp.img   lubuntu_1804-flat.vmdk  memtest.efi  undionly.kpxe
ltsp.ipxe  lubuntu-flat.vmdk       raspbian     x86_64
lubuntu    memtest.0               snponly.efi
root@ltsp:~# ls /srv/tftp/ltsp/raspbian/
root@ltsp:~# 
```

**Comment by alkisg** [comment]
Aah you probably don't have the proposed PPA in your sources, so you're using the old LTSP.

**Comment by alkisg** [comment]
Yes, 20.01 isn't yet in the stable repository, it's only in proposed:

https://ltsp.org/advanced/proposed-ppa/

**Comment by seancarte** [comment]
That was it, thanks, @alkisg .

Unfortunately the pi won't ack the DHCPOFFER:

```
Jan 21 11:01:24 ltsp dnsmasq-dhcp[802]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:01:24 ltsp dnsmasq-dhcp[802]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:01:26 ltsp dnsmasq-dhcp[802]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:01:26 ltsp dnsmasq-dhcp[802]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:01:31 ltsp dnsmasq-dhcp[802]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:01:31 ltsp dnsmasq-dhcp[802]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:01:36 ltsp dnsmasq-dhcp[802]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:01:36 ltsp dnsmasq-dhcp[802]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:01:41 ltsp dnsmasq-dhcp[802]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:01:41 ltsp dnsmasq-dhcp[802]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
```

The pi is connected to the server's np1s1 port via a crossover cable. Since it does get an address when booting from the SD card, I assume that the config is working:

```
Jan 21 11:07:16 ltsp dnsmasq-dhcp[802]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:07:16 ltsp dnsmasq-dhcp[802]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:07:16 ltsp dnsmasq-dhcp[802]: DHCPREQUEST(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:07:16 ltsp dnsmasq-dhcp[802]: DHCPACK(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18 raspberrypi
```

Sorry, I'm stuck again.

**Comment by alkisg** [comment]
Run `ltsp dnsmasq` again with the new version.

**Comment by seancarte** [comment]
Great. With that, I was able to boot the pi. Added the PPA (ppa:ltsp) and installed ltsp. Updated cmdline.txt and created the squashfs image.

But on booting the pi, I get the error on the pi: 

> Refusing to run client applet init in non-ltsp client
> LTSP boot error! Enable DEBUG_SHELL to troubleshoot!

I added
DEBUG_SHELL=1
to the [common] section of ltsp.conf, but that hasn't made any difference.

This is what is in syslog:
```
Jan 21 11:55:03 ltsp dnsmasq-dhcp[11648]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:55:03 ltsp dnsmasq-dhcp[11648]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:55:03 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/bootcode.bin to 192.168.67.65
Jan 21 11:55:03 ltsp dnsmasq-tftp[11648]: file /srv/tftp/bootsig.bin not found
Jan 21 11:55:03 ltsp dnsmasq-dhcp[11648]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:55:03 ltsp dnsmasq-dhcp[11648]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:55:03 ltsp dnsmasq-tftp[11648]: file /srv/tftp/b09aec18/start.elf not found
Jan 21 11:55:03 ltsp dnsmasq-tftp[11648]: file /srv/tftp/autoboot.txt not found
Jan 21 11:55:03 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/config.txt to 192.168.67.65
Jan 21 11:55:03 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery.elf not found
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/start.elf to 192.168.67.65
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/fixup.dat to 192.168.67.65
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery.elf not found
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/config.txt to 192.168.67.65
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: file /srv/tftp/dt-blob.bin not found
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery.elf not found
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/config.txt to 192.168.67.65
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: file /srv/tftp/bootcfg.txt not found
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/bcm2710-rpi-3-b-plus.dtb to 192.168.67.65
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/config.txt to 192.168.67.65
Jan 21 11:55:04 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/cmdline.txt to 192.168.67.65
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery8.img not found
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery8-32.img not found
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery7.img not found
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: file /srv/tftp/recovery.img not found
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: file /srv/tftp/kernel8-32.img not found
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: error 0 Early terminate received from 192.168.67.65
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: failed sending /srv/tftp/kernel8.img to 192.168.67.65
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: error 0 Early terminate received from 192.168.67.65
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: failed sending /srv/tftp/kernel7.img to 192.168.67.65
Jan 21 11:55:07 ltsp dnsmasq-tftp[11648]: file /srv/tftp/armstub8-32.bin not found
Jan 21 11:55:08 ltsp dnsmasq-tftp[11648]: sent /srv/tftp/kernel7.img to 192.168.67.65
Jan 21 11:55:10 ltsp kernel: [10880.482606] r8169 0000:01:01.0 enp1s1: Link is Down
Jan 21 11:55:16 ltsp NetworkManager[699]: <info>  [1579600516.3994] device (enp1s1): carrier: link connected
Jan 21 11:55:16 ltsp kernel: [10886.109459] r8169 0000:01:01.0 enp1s1: Link is Up - 1Gbps/Full - flow control off
Jan 21 11:55:17 ltsp dnsmasq-dhcp[11648]: DHCPDISCOVER(enp1s1) b8:27:eb:9a:ec:18
Jan 21 11:55:17 ltsp dnsmasq-dhcp[11648]: DHCPOFFER(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:55:17 ltsp dnsmasq-dhcp[11648]: DHCPREQUEST(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:55:17 ltsp dnsmasq-dhcp[11648]: DHCPACK(enp1s1) 192.168.67.65 b8:27:eb:9a:ec:18
Jan 21 11:55:17 ltsp rpc.mountd[10688]: authenticated mount request from 192.168.67.65:722 for /srv/ltsp/raspbian (/srv/ltsp/raspbian)
```

**Comment by alkisg** [comment]
You need the proposed PPA on the client as well. 19.12 doesn't support Raspberries.

**Comment by seancarte** [comment]
I changed cmdline.txt back to allow NFS_RW netbooting; installed the proposed PPA on the client; restored the cmdline.txt and recreated the squashfs image.

The pi gets a little further, but eventually stops with:
```
grep: /proc/cmdline: No such file or directory
/usr/sbin/tsp: 94: /usr/sbin/ltsp: cannot create /etc/hostname: Read-only file system
/usr/sbin/tsp: 99: /usr/sbin/ltsp: cannot create /etc/hosts: Read-only file system
LTSP command failed: config_hosts
Aborting ltsp
LTSP boot error! Enable DEBUG_SHELL to troubleshoot!
```
I redid all the steps from Server Preparation just to be certain I hadn't missed anything, but it still stops at the same point.

**Comment by alkisg** [comment]
Hmm strange, it looks like the writable overlay isn't applied.
Let's do what I wrote [above](https://github.com/ltsp/ltsp/issues/68#issuecomment-576013033) and wait a bit until someone is willing to fund automation of the procedure and documentation review; things will be much easier after that.

**Comment by seancarte** [comment]
I'll revert to using NFS_RW netbooting for now.

Thank you, @alkisg , for being so generous with your time and patient with me.

Regarding the documentation, I can recommend a couple of changes:
s/preperation/preparation/g
and perhaps a note to use the Proposed PPA, though I imagine you didn't want to have to go back and change that when the proposed PPA becomes the stable?

**Comment by alkisg** [comment]
> I'll revert to using NFS_RW netbooting for now.

Keep in mind that you can only netboot a single client that way, without risking chroot corruption.

>  s/preperation/preparation/g

Thanks, done!

> a note to use the Proposed PPA

Within a couple of weeks, 20.0x will be in the stable PPA so there won't be need for the proposed PPA. But I did add a note at the top of the page that currently my remote support is needed for Raspberries in LTSP; that too will be removed after the first few installations which will gather enough funding to finish everything.

Cheers!

**Comment by alkisg** [comment]
A kernel update landed on Raspbian, 4.19.93. Of course this doesn't affect LTSP, it still works fine with any kernel.

But I was curious to test if the pipxe method issues were gone with the new kernel.
It turns out that https://github.com/ipxe/pipxe/issues/1 is resolved and there's no black screen anymore and there's no need for kernels outside of the repositories.
But the colors are still inverted so the pipxe method still isn't really usable.

LTSP uses bootcode.bin and not pipxe so we don't really care, but if the pipxe method ever ends up working well, it will also automatically work with LTSP too, and it will give us a nice iPXE menu.

**Comment by mherweg** [comment]
I followed your instructions and now I'm stuck at:
ltsp kernel raspbian
Could not locate vmlinuz and initrd.img in raspbian

It's true. raspbian /boot does not have those files. only kernel*.img ...
VERSION='20.01-1~202001301202~ubuntu18.04.1'

**Comment by alkisg** [comment]
Hi @mherweg, you missed the part about putting RPI_IMAGE in ltsp.conf:

https://ltsp.org/docs/installation/raspbian/#server-preparation

**Comment by mherweg** [comment]
thank you for your very fast answer. I did not know the correct location of ltsp.conf. I now did:
cp /usr/share/ltsp/common/ltsp/ltsp.conf /etc/ltsp
ltsp kernel raspbian
ltsp initrd
ltsp nfs

I tried to boot a Pi3 and see this in the server's log:
"nicht gefunden" = "not found"
Feb 12 15:00:57 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/27e90cf7/start.elf nicht gefunden
Feb 12 15:00:57 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/autoboot.txt nicht gefunden
Feb 12 15:00:57 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/config.txt to 192.168.8.199
Feb 12 15:00:57 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery.elf nicht gefunden
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/start.elf to 192.168.8.199
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/fixup.dat to 192.168.8.199
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery.elf nicht gefunden
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/config.txt to 192.168.8.199
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/dt-blob.bin nicht gefunden
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery.elf nicht gefunden
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/config.txt to 192.168.8.199
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/bootcfg.txt nicht gefunden
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/cmdline.txt to 192.168.8.199
Feb 12 15:00:59 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/bcm2710-rpi-3-b.dtb to 192.168.8.199
Feb 12 15:01:00 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/config.txt to 192.168.8.199
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery8.img nicht gefunden
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery8-32.img nicht gefunden
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery7.img nicht gefunden
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/recovery.img nicht gefunden
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/kernel8-32.img nicht gefunden
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: **error 0 Early terminate received from 192.168.8.199**
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: **failed sending /srv/tftp/kernel8.img to 192.168.8.199**
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: **error 0 Early terminate received from 192.168.8.199**
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: **failed sending /srv/tftp/kernel7.img to 192.168.8.199**
Feb 12 15:01:02 lenovoT500 dnsmasq-tftp[16950]: Datei /srv/tftp/armstub8-32.bin nicht gefunden
Feb 12 15:01:05 lenovoT500 dnsmasq-tftp[16950]: sent /srv/tftp/kernel7.img to 192.168.8.199

**Comment by alkisg** [comment]
These tftp logs are fine, do not mind either the kernel8.img nor the failure-and-then-success message of kernel7.img. The same logs will appear on successful boot.

You might want to remove quiet splash from cmdline.txt, and put plymouth.enable=0, to better see error messages.

**Comment by mherweg** [comment]
The „NFS_RW“ Network boot was successful. I continued to follow the Instructions. It is not always 100% clear what to do on the server and what on the client, but I think I got it right. 
The LTSP Boot fails at: **Run /usr/share/ltsp/client/init/init as init process
grep: /proc/cmdline: No such file or directory.**

Maybe my mistake was, that I used the stable PPA and not the "proposed"  PPA on the Client, but both state the same LTSP Version: 20.01-1

**Comment by alkisg** [comment]
I don't think you did any mistakes; booting a single client with the NFS_RW network boot is as far as it goes for now.
As stated in https://ltsp.org/docs/installation/raspbian/, in https://github.com/ltsp/ltsp/issues/68#issuecomment-576742049 and in https://github.com/ltsp/ltsp/issues/68#issuecomment-577037402, the rest of the process currently needs remote support from me.
When some funding is found, I'll be able to work on updating the instructions and make sure that all parts work for everyone.

**Comment by dmit2k** [comment]
Hello @alkisg and hope you are doing well!

Just to note that I've met the same issue with PRi4 booting:

Boot fails at: Run /usr/share/ltsp/client/init/init as init process
grep: /proc/cmdline: No such file or directory.

and some lines stating that ltsp cannot create hostname and hosts files due to read-only filesystem.

Looks like an issue with RW overlay not being applied... Any ideas on how to fix or debug the issue any further?.. 

I understand that you're waiting for additional funding, but maybe that could turn out as a small and not time-consuming fix?..

**Comment by alkisg** [comment]
Hi dmit2k, as I [wrote above](https://github.com/ltsp/ltsp/issues/68#issuecomment-576013033), it's mostly a matter of past work done in January, not current or future work. I've given years of volunteer work for LTSP and lots of other open source projects because we use them in schools here. But we're not using Raspberries, so there's no point in me developing or maintaining support for them in LTSP, unless rpi developers or users step up and contribute either code or funding. So far, only two rpi users have contributed, so it might take a while! :)

Maybe it would be more sustainable to offer LTSP rpi support as a non-free open source addon; but coding doesn't leave me enough time to do that, someone else would need to organize it...

**Comment by alkisg** [comment]
Raspbian should now be fully supported, closing.
