### ISSUE TITLE
ltsp command failed while booting the image

### ISSUE THREAD

**Issue by pietus** [ltsp/ltsp#693]
Hi,
after a server change to debian bullseye the working images don't start anymore with error message:

`ltsp command failed: /usr/share/ltsp/client/login/pwmerge -lq /etc/ltsp /etc /etc`

I installed ltsp following: [https://ltsp.org/docs/installation/](url)
and installed virtualbox and its VMs to its locations linked to /srv/ltsp and generated the images new with `ltsp image imagename` without problems.

Starting the image from the client ends in upper error.
What am I doing wrong?
pietus

**Comment by alkisg** [comment]
Hi, ltsp issues are for bugs; please open a discussion instead:

https://github.com/ltsp/ltsp/discussions
