### ISSUE TITLE
EN DASH in online man pages

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#71]
In online man pages, two hyphens are converted to EN DASH.
For example, in https://ltsp.github.io/man/ltsp/, this line:

> -b, –base-dir=/srv/ltsp

should instead be:

> -b, --base-dir=/srv/ltsp

**Comment by alkisg** [comment]
In [this stackoverflow question](https://stackoverflow.com/questions/16871088/how-to-escape-double-dash-in-markdown) they mention a "smart" extension for the "redcarpet" markdown parsing library, but I'm not sure that's the one github uses; I couldn't make it work.

Temporary workaround committed, it avoids *most* of EN DASHes.
