### ISSUE TITLE
ACUTE ACCENT in local man pages

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#72]
In local man pages, single quotes are converted to acute accents, for example in `man ltsp.conf`, this line:

```shell
sed ´s|^root:...
```

should instead be:

```shell
sed 's|^root:...
```

**Comment by alkisg** [comment]
This is an issue with Ronn, see https://github.com/rtomayko/ronn/pull/83#issuecomment-554651510.

Thanks, workaround committed in https://github.com/ltsp/ltsp/commit/6350cbf1e4b7f85dbf845a5ef23831a05007a06d.
