### ISSUE TITLE
Unicode quotation marks in online man pages

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#73]
From [https://ltsp.github.io/man/ltsp.conf/](https://ltsp.github.io/man/ltsp.conf/):

```shell
AUTOLOGIN=“user01”
```

The quotes there are unicode characters 'LEFT/RIGHT DOUBLE QUOTATION MARK' (U+201C/201D)', they're invalid for ltsp.conf.

**Comment by alkisg** [comment]
Thanks, fix committed.
