### ISSUE TITLE
Add support for loading image to RAM

### ISSUE THREAD

**Issue by kvaps** [ltsp/ltsp#74]
LTSP5 was support LTSP_NBD_TO_RAM option, which allows to copy image into RAM during the boot.

The booted client does not need to rely on network connection, server status, it can just work until it will be rebooted.

This dry stability is exactly what we needed for use LTSP to organize our network booting farm.

**Comment by alkisg** [comment]
This should already be doable with the existing code, with a couple of PRE_INITRD_BOTTOM_* commands.

Since only a few LTSP users need this, maybe a wiki page with those 2 commands would be better than supporting it in the code, as it would allow to explain the limitations; e.g. a chroot can't easily go to RAM, it needs to be an image.

I think something like this would be a starting point:

```shell
PRE_INITRD_BOTTOM_IMAGE_TO_RAM="
dd if=/root/x86_64.img of=/run/initramfs/x86_64.img bd=1M status=progress
umount /root
mount -o ro /run/initramfs/x86_64.img /root
"
```

**Comment by jphein** [comment]
Was browsing github. I found this interesting: https://github.com/selivan/thinclient

**Comment by kvaps** [comment]
Thanks for answers, I'll check this opportunity, this feature for LTSP5 was quite usable in russian community for some other peoples.
I may ask them again.

**Comment by kvaps** [comment]
OK, I've asked them to add "👍" for vote this issue

**Comment by kvaps** [comment]
BTW, this hook is working:
```ini
[clients]
PRE_INITRD_BOTTOM_IMAGE_TO_RAM="
initrd_bottom_main() {
    kernel_vars
    re cp /root/\$IMAGE /run/initramfs/\${IMAGE##*/}
    re umount /root
    re mount -t squashfs -o ro /run/initramfs/\${IMAGE##*/} /root
    re modprobe_overlay
    re overlay \"\$rootmnt\" \"\$rootmnt\" \"/run/initramfs/ltsp\"
    re install_ltsp
}
"
```

**Comment by kvaps** [comment]
For those who just found this issue, we've added new function for handle this behavior:

```
IMAGE_TO_RAM=1

Specifying this option under the [clients] section copies the rootfs
image to RAM during boot. That makes clients less dependent on
the server, but they must have sufficient memory to fit the image.
```
