### ISSUE TITLE
Support arctica-greeter

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#742]
Ubuntu 20.04 used `slick-greeter` as the login screen.
In Ubuntu 22.04 it was replaced by `arctica-greeter`.

This change made the LTSPDM_USERS ltsp.conf parameter not work in Ubuntu 22.04, please add support for it.

**Comment by alkisg** [comment]
Committed a fix and uploaded a PPA build; please test if it solves the issue.

**Comment by fottsia** [comment]
Works for me, closing.
