### ISSUE TITLE
Boot error with kernel ≥ 5.15 - "overlayfs: failed to retrieve lower fileattr"

### ISSUE THREAD

**Issue by jperon** [ltsp/ltsp#745]
After upgrading chroot to Ubuntu 22.04, boot hangs with `overlayfs: failed to retrieve lower fileattr`. When downgrading kernel to 5.14 (or 5.10, as it’s LTS) thanks to [kernel ppa](https://kernel.ubuntu.com/~kernel-ppa/mainline/), it boots normally. But with kernel 5.15, it gives this error (and also with 6.0rc).

Below a screenshot of the problem.

![VirtualBox_ClientLourd_30_08_2022_09_44_52](https://user-images.githubusercontent.com/4775231/187399456-cad816aa-5421-422d-961b-13e6fbd1b34e.png)

**Comment by alkisg** [comment]
Hi, I've been testing Ubuntu 22.04 since last November with no issues.
My last installation with Ubuntu MATE 22.04 and kernel 5.15 was done a week ago and the clients booted successfully.
This appears to be a local issue with your installation.
When the problem happens, is /root mounted? What are its contents?

**Comment by jperon** [comment]
Here is the result of the commands to list mounts and content of /root/sbin/ (restricted to `i*` to stay concise):

![remmina_servus:3390_servus:3390_20220830-200958](https://user-images.githubusercontent.com/4775231/187536368-13bcc376-c1b8-4bb1-ae23-c05112417b7b.png)

![remmina_servus:3390_servus:3390_20220830-201132](https://user-images.githubusercontent.com/4775231/187536396-90d98275-f3d1-4988-afe4-63ce212ed613.png)

**Comment by alkisg** [comment]
Are you using the stock 5.15 Ubuntu kernel, or the mainline PPA one?
Inside the chroot, what's the output of `dpkg -l | grep linux` ?
When the client boots, what's the output of `uname -a` ?

Attaching a screenshot of a successful boot using the latest Ubuntu 5.15 kernel.

![VirtualBox_shared_31_08_2022_10_11_04](https://user-images.githubusercontent.com/88025/187616140-a226eb20-4bec-441d-9c6a-62e352a91afc.png)

**Comment by jperon** [comment]
I’m using `linux-generic-hwe-22.04`, which for now depends on `linux-image-5.15.0-25-generic`.
While investigating, I saw that the problem only occurs when booting the chroot over NFS. When using `ltsp image CHROOT`, then booting on `CHROOT.img`, it works.

Screenshot when booting over NFS:

![SKLUEW~K](https://user-images.githubusercontent.com/4775231/187618549-53dfdf05-48f7-4552-9dca-be369a2db94d.PNG)

**Comment by alkisg** [comment]
Ah sure, overlayfs over plain NFS (not squashfs/vmdk image) has always had its issues.
You need to report that one to the kernel bug tracker, there's nothing we can do about it from the LTSP code base.

Btw, it's 5.15.0-46, not -25; you may want to check if you're missing the ubuntu updates repository:

```shell
$ apt policy linux-generic-hwe-22.04
linux-generic-hwe-22.04:
  Candidate: 5.15.0.46.46
```
