### ISSUE TITLE
SSSD autodetection in pamltsp doesn't work if /etc/sssd/conf.d is used instead of /etc/sssd/sssd.conf

### ISSUE THREAD

**Issue by MAccadia** [ltsp/ltsp#749]
Hi,

I have noticed that `pamltsp` only check for `/etc/sssd/sssd.conf` although SSSD also supports having its configuration in `/etc/sssd/conf.d` : 
https://github.com/ltsp/ltsp/blob/891b9941d1bb545b0ef2f017409bb2b12cf5009e/ltsp/client/login/pamltsp#L306

I have added `PAM_AUTH_TYPE="Additional"` to my `ltsp.conf` as a workaround.

Best regards

Ubuntu 20.04.5 LTS 
LTSP 22.01-1~ubuntu20.04.1

**Comment by alkisg** [comment]
Hi, Ubuntu live CDs have sssd preinstalled (so in pam.d) but not in use (so no sssd.conf). The sssd.conf check aims to keep pamltsp enabled in such cases.

Are there (or will there ever be) any Debian/Ubuntu packages that ship files in /etc/sssd/conf.d? If so, then we shouldn't use the contents of that directory for autodetection.

The `find /var/lib/sss -type f` command returns some files like `sssd.ldb`, does the presence of any of these files guarantee that sssd has been configured by the administrator?

**Comment by MAccadia** [comment]
Yes, [the patch](https://github.com/ltsp/ltsp/commit/c632102847da982703def4286f7f26f014303548) works for me.

As an alternative, we can detect sssd with : 
```bash
if systemctl --quiet is-active sssd
then ... 
fi
```
It does seem to check on the configurations files : 
```bash
> systemctl status sssd
● sssd.service - System Security Services Daemon
     Loaded: loaded (/lib/systemd/system/sssd.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
  Condition: start condition failed at Wed 2022-09-14 09:47:15 CEST; 22s ago
             ├─ ConditionPathExists=|/etc/sssd/sssd.conf was not met
             └─ ConditionDirectoryNotEmpty=|/etc/sssd/conf.d was not met
```
and we get the benefit of avoiding false positive when config files are present and sssd service is disabled.

**Comment by alkisg** [comment]
The `pamltsp install` code runs at init, before systemd is loaded; no services at all are running at that point.
Thanks, closing with the already committed patch.
