### ISSUE TITLE
Permissions for mkhomedir emulation

### ISSUE THREAD

**Issue by MAccadia** [ltsp/ltsp#754]
Hi,

pamltsp currently emulates pam_mkhomedir with hardcoded permissions (see [pamltsp#L156](https://github.com/ltsp/ltsp/blob/c632102847da982703def4286f7f26f014303548/ltsp/client/login/pamltsp#L156)).

Would it be possible to make it configurable ?

Maybe we could also change the default permissions to `0750` since it's [now the default on Ubuntu 21+](https://lists.ubuntu.com/archives/ubuntu-devel/2021-January/041318.html).

**Comment by alkisg** [comment]
Hi @MAccadia, the permissions of the directory that is created on client:/home/username do not matter.
Once server:/home/username is mounted over client:/home/username via SSHFS, the server permissions will be used.
Feel free to reopen the issue if that's not the case.
