### ISSUE TITLE
NFS 4 support

### ISSUE THREAD

**Issue by MAccadia** [ltsp/ltsp#759]
Hi,

I needed to make LTSP work with a firewall. It works but NFS 3 is not very well suited (I followed https://wiki.debian.org/SecuringNFS). It would be nice to have NFS 4 support.

I don't have high hopes though ; it seems to be a initramfs / klibc limitation (see [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=409271)).

The best strategy is probably to wait for klibc to support NFS4 rootfs.

**Comment by alkisg** [comment]
Indeed, the NFSv4 support cannot be added in the LTSP code base, it needs to be added in initramfs-tools.

Dracut is said to have NFSv4 support, but dracut in Debian has its own issues.

I followed that SecuringNFS page a couple of years ago with good results, in that installation we do have `ufw` active in both LTSP servers and clients.

Another idea would be to use [LTSP over wireguard](https://github.com/ltsp/ltsp/issues/127); then all services, NFSv3 included, will be firewall friendly and secure.

I'll close this issue as I don't think it requires any action from the LTSP side; if anyone thinks we can somehow help, feel free to re-open it.
