### ISSUE TITLE
Avoid systemd lingering

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#778]
Some Linux Mint installations enable systemd lingering by default.
This means that systemd starts user sessions even before they login.
This means that pulseaudio is started for them.
The result is that pulseaudio is in use when another user logs in, and they get no sound.

A solution is to exclude these files from the image: /var/lib/systemd/linger/*

...I'll add a commit for that.

**Comment by alkisg** [comment]
Fix committed, please test if this resolves the issue.

**Comment by fottsia** [comment]
I tested with a LinuxMint installation, it seems to work for me, closing.
