### ISSUE TITLE
Record Locking Mint Vanessa

### ISSUE THREAD

**Issue by knightflyer** [ltsp/ltsp#782]
### Discussed in https://github.com/ltsp/ltsp/discussions/781

<div type='discussions-op-text'>

<sup>Originally posted by **knightflyer** December 18, 2022</sup>
NFS record locking does not work between ltsp clients with my current configuration.
However works perfectly between ltsp client and server or other nfs connected hosts.
Getting ready to implement my client's big upgrade after a year. Glad I found this before upgrading the client.

NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
UBUNTU_CODENAME=jammy

Here are my server's /etc/exports entries:

/u    192.168.1.0/24(rw,sync,all_squash,anonuid=1001,anongid=1001,no_subtree_check)

My /etc/ltsp/ltsp.conf entry :

FSTAB_x="192.168.1.200:/u /u nfs defaults 0 0"

Thank you everyone for the help.
</div>

**Comment by alkisg** [comment]
This is discussed in #781, closing from issues as it's not related to the LTSP codebase.
