### ISSUE TITLE
LTSP command failed: mount -t squashfs -o ro /root/images/debian-flat.vmdk.img /run/initranfs/ltsp/0/looproot

### ISSUE THREAD

**Issue by Rothammel** [ltsp/ltsp#786]
I have created a virtual Debian VM box image, which is described here:
https://ltsp.org/man/ltsp-image/
On the client side, this error appears:
LTSP command failed: mount -t squashfs -o ro /root/images/debian-flat.vmdk.img /run/initranfs/ltsp/0/looproot

![image](https://user-images.githubusercontent.com/42540450/213937661-86a4a51b-c05e-4dd5-b68c-564b6ca53ce8.png)

**Comment by alkisg** [comment]
Hi, what's the output of the following commands on your server?

```shell
sudo -i
ls -l /srv/ltsp/images/
file /srv/ltsp/images/*
fdisk -l /srv/ltsp/images/*
```

Btw "issues" are for bugs, while to request help the "discussions" are appropriate.

**Comment by Rothammel** [comment]
apologies for the incorrect use 
```
sudo -i
-bash: sudo: Kommando nicht gefunden.

ls -l /srv/ltsp/images/
insgesamt 608596
-rw-r--r-- 1 root root 297238528 22. Jan 20:50 debian-flat.vmdk.img
-rw-r--r-- 1 root root 325963776 22. Jan 20:22 debian-monero-flat.vmdk.img

file /srv/ltsp/images/*
/srv/ltsp/images/debian-flat.vmdk.img:        Squashfs filesystem, little endian, version 4.0, zlib compressed, 297234968 bytes, 34283 inodes, blocksize: 131072 bytes, created: Sun Jan 22 19:50:44 2023
/srv/ltsp/images/debian-monero-flat.vmdk.img: Squashfs filesystem, little endian, version 4.0, zlib compressed, 325962646 bytes, 34382 inodes, blocksize: 131072 bytes, created: Sun Jan 22 19:22:31 2023

fdisk -l /srv/ltsp/images/*
Disk /srv/ltsp/images/debian-flat.vmdk.img: 283,47 MiB, 297238528 bytes, 580544 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /srv/ltsp/images/debian-monero-flat.vmdk.img: 310,86 MiB, 325963776 bytes, 636648 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Comment by alkisg** [comment]
The symlinks to the VMs should be named like:
/srv/ltsp/debian.img
/srv/ltsp/debian-monero.img

Then you should run `ltsp image debian` or `ltsp image monero`.

Then the resulting squashfs images will be:
/srv/ltsp/images/debian.img
/srv/ltsp/images/debian-monero.img

**Comment by ricpelo** [comment]
Sorry for bumping this, but I have the same issue. I'm using Debian bookworm.
![IMG_20241025_212639.jpg](https://github.com/user-attachments/assets/49f0557d-50b1-443f-b73b-5b4275e3763a)

**Comment by ricpelo** [comment]
Sorry, I forgot to install the `ltsp` package on client image. Doing so now the issue is solved. Thanks.
