### ISSUE TITLE
Configure printing

### ISSUE THREAD

**Issue by alkisg** [ltsp/ltsp#8]
The new LTSP currently doesn't handle printing at all.

This means that if the sysadmin runs `cupsctl _share_printers=1` or goes to the cups UI and enables printer sharing, either on the server or the clients, all printers will be automatically discoverable via CUPS.

But the old jetpipe tool isn't available; which was used to forward a client printer port to the server, so that the driver installation would then happen on the server instead of the chroot. This helped in cases where the printer didn't ship a ppd and wasn't autodetected. For jetpipe to be included, it would have to be rewritten in python3; alternatively, [p910nd](http://p910nd.sourceforge.net/) could be used.

[Driverless printing](https://wiki.debian.org/DriverlessPrinting) should also be considered while searching for the best solution.

**Comment by alkisg** [comment]
Method 1: managing all the printers on the LTSP server.

This method involves enable printer sharing on the server either via the GUI (`system-config-printer` or http://localhost:631) or by running `sudo cupsctl _share_printers=1`, and putting the following in ltsp.conf:

```shell
[clients]
echo "ServerName $SERVER" > /etc/cups/client.conf
```

Then all printers are managed on the server, and the clients just connect to the server cups and access the available printers from there.

**Comment by alkisg** [comment]
Fix committed in 184687e8807b41c5916bf265bd516ae4f85c19a2.
CUPS_SERVER is documented in ltsp.conf; CUPS_SERVER="ignore" allows the LTSP administrator to manually configure /etc/cups/client.conf.

**Comment by fottsia** [comment]
I installed the drivers for a network printer in my VM image, and I wanted all clients to have access to it directly, without sharing it from the LTSP server. In addition to CUPS_SERVER="ignore", I had to use OMIT_FUNCTIONS in order to keep the /etc/cups/printers.conf file from being replaced:

```shell
[server]
OMIT_FUNCTIONS="remove_printers"

[clients]
CUPS_SERVER="ignore"
```

**Comment by svetoi1985** [comment]
How do I configure ltsp.conf to transfer certain printers to terminal clients and not display everything and for everyone.

**Comment by svetoi1985** [comment]
It is necessary to share printers, let's say the office costs 1 printer in 1 office and 3 terminal clients who only need this printer, in 2 office there are 2 printers for 6 clients. so that only your printers can be seen in each office. USB printers were installed from customers and made their way through jetpip.

**Comment by alkisg** [comment]
See the relevant discussion: https://github.com/ltsp/ltsp/discussions/520

**Comment by renatogfilhinho** [comment]
Hello, please, how can I leave network printer discovery active for clients and also leave the CUPS service active, as well as allowing clients to also access other machines through Remmina? Thank you very much!!!
