### ISSUE TITLE
memtest binary needs renaming

### ISSUE THREAD

**Issue by schweer-guest** [ltsp/ltsp#801]
memtest86+ has renamed the 32bit binary (again). [xe](https://github.com/ltsp/ltsp/tree/main/ltsp/server/ipxe)/55-ipxe: s/x32.bin/ia32.bin/

**Comment by alkisg** [comment]
Fix committed, thanks!
@vagrantc, @schweer-guest, do we need this for bookworm?
From what I'm reading, soft feature freeze allows such small changes, right?
If so, should I make a new 23.02-1 micro-release, or do we want this in debian/patches?

**Comment by schweer-guest** [comment]
@alkisg yes, needed for bookworm. And yes, it is allowed (small, targeted fix)
