### ISSUE TITLE
`ltsp image` fails with pwmerge error on Ubuntu 22 Server

### ISSUE THREAD

**Issue by emendir** [ltsp/ltsp#888]
I'm using the virtual machine method to create LTSP client images.

I want to create an LTSP client image based on Ubuntu 22 Server (because that OS supports automatic installation, which is needed by my installation systems; my scripts install a GUI on the VM).

The virtual machine I create for it works fine, but when I try to create an LTSP image from it using the command `ltsp image $IMAGE_NAME`, it fails with the following error:
```
Running: losetup -rP /dev/loop13 /srv/ltsp/Ubuntu.img
Running: mount -t tmpfs -o mode=0755 tmpfs /tmp/tmp.FT1jlT4IaW/tmpfs
Running: mount -t ext4 -o ro,noload /dev/loop13p2 /tmp/tmp.FT1jlT4IaW/tmpfs/0/looproot

Running: mount -t overlay -o upperdir=/tmp/tmp.FT1jlT4IaW/tmpfs/0/up,lowerdir=/tmp/tmp.FT1jlT4IaW/tmpfs/0/looproot,workdir=/tmp/tmp.FT1jlT4IaW/tmpfs/0/work /tmp/tmp.F
T1jlT4IaW/tmpfs /tmp/tmp.FT1jlT4IaW/root/
Cleaning up Ubuntu before mksquashfs...
Traceback (most recent call last):
  File "/usr/share/ltsp/client/login/pwmerge", line 440, in <module>
    main(sys.argv)
  File "/usr/share/ltsp/client/login/pwmerge", line 434, in main
    pwm = PwMerge(args[0], args[1], args[2], **dopts)
  File "/usr/share/ltsp/client/login/pwmerge", line 117, in __init__
    self.dpasswd, self.dgroup = self.read_dir(ddir, dur or dgr)
  File "/usr/share/ltsp/client/login/pwmerge", line 151, in read_dir
    with open("{}/passwd".format(xdir), "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp.FT1jlT4IaW/root/etc/passwd'
LTSP command failed: /usr/share/ltsp/client/login/pwmerge --ltsp --quiet /tmp/tmp.FT1jlT4IaW/root/tmp/pwempty /tmp/tmp.FT1jlT4IaW/root/etc /tmp/tmp.FT1jlT4IaW/root/tmp/pwmerged
Aborting ltsp
```

If I use a Ubuntu Desktop image instead of Ubuntu Server, everything works fine.

Does anybody understand this error?
Would a bugfix for this issue be feasible to develop in the LTSP code?
Is there a workaround I could implement before that bugfix is released?

**Comment by alkisg** [comment]
Your image is not appropriate (either missing /etc/passwd or wrong partitions), sorry this period I don't have enough time to post lengthy troubleshooting instructions, you may come from Matrix for VNC-based live support:

https://ltsp.org/guides/chat-room/

**Comment by emendir** [comment]
Thanks for your help! Your suggestion about the partitions led me to the solution.

The problem was that Ubuntu server sets up its partitions using LVM by default. I disabled LVM storage in the virtual machine's automated installation, and now LTSP can create an image from it.
