### ISSUE TITLE
Global KERNEL_PARAMETERS

### ISSUE THREAD

**Issue by kvaps** [ltsp/ltsp#95]
There is need option to specify `KERNEL_PARAMETERS` option globally in [server] section and via environment variables

example usage:
```ini
export KERNEL_PARAMETERS="forcepae console=tty1 console=ttyS0,9600n8"
ltsp ipxe
```

**Comment by kvaps** [comment]
Reliable workaround:
```ini
export POST_IPXE_SED="sed -i '/^set cmdline_method/ s|$| forcepae console=tty1 console=ttyS0,9600n8|g' /srv/tftp/ltsp/ltsp.ipxe"
ltsp ipxe
```

**Comment by alkisg** [comment]
Thank you kvaps,

if we apply #110, then global KERNEL_PARAMETERS can then be defined under [server] or [common], but not under [clients]. Is this OK, or will it confuse our users?

**Comment by kvaps** [comment]
Yes, the same way for MENU_TIMEOUT and for DEFAULT_IMAGE (not implemented?)

Well we can add `section_call client` before the executing, or just note about this feature in the ltsp.conf docs. Anyway we're not supporting all clients sections, but only mac-address for now.

**Comment by alkisg** [comment]
Thanks, PR merged.

I'll check if the same can be done for DEFAULT_IMAGE easily.

**Comment by alkisg** [comment]
DEFAULT_IMAGE was a bit more tricky... we could define DEFAULT_IMAGE_x86_64 and DEFAULT_IMAGE_x86_32 to sed the `cpuid` line with them, and/or we could define a global DEFAULT_IMAGE for cases where one wanted e.g. all  clients to reboot to memtest quickly.

I opted for the second implementation for simplicity, and updated ltsp.conf accordingly.
