### ISSUE TITLE
Consider setting correct IP in hosts

### ISSUE THREAD

**Issue by kvaps** [ltsp/ltsp#97]
Some services might fail when hostname is not resolving to correct ip address, so I use the next hook for make `ipa-client` working:
```ini
POST_INIT_FIX_HOSTS = "sed -i \"s/^127.0.1.1/\${IP_ADDRESS}/g\" /etc/hosts"
```
Shouldn't we add this setting by default?

**Comment by alkisg** [comment]
In my workstation, I have a static IP, and I don't have an entry for my hostname in /etc/hosts:

```shell
127.0.0.1	localhost
127.0.1.1	alkis
```

I think we should default to that. If a program doesn't like that and needs workarounds, then it can be documented in a wiki page etc, but it shouldn't be the default for LTSP.

**Comment by kvaps** [comment]
`127.0.1.1` - but this is local IP, what the purpose of specifying this while we have normal real IP address?

I can explain you this problem more detailed, eg. when we having configured A record on our DNS-server:

which is visible for everyone like:
```bash
# getent ahosts alkis
10.28.36.171    STREAM alkis.office.local
10.28.36.171    DGRAM  
10.28.36.171    RAW    
```

but your pc will is alone, who will have wrong value for this record:
```
# getent ahosts alkis
127.0.1.1       STREAM alkis
127.0.1.1       DGRAM  
127.0.1.1       RAW    
```

**Comment by alkisg** [comment]
Suppose you have a LAN **without LTSP** and with all clients having **dynamic** IP.
What would you put in their /etc/hosts?

**Comment by kvaps** [comment]
I'd like to put correct IP-address specified in $IP_ADDRESS variable on init-stage, or leave it empty.
Both variants are acceptable, but I thinking that first is more correct.

BTW, we're already using this setup for 3 years with LTSP5, it is working pretty fine.

**Comment by alkisg** [comment]
LTSP tries to imitate what local installations do. Debian and Ubuntu put `127.0.0.1 hostname` there, so we've been doing the same thing in LTSP5 for 10+ years now. I don't know why you say that LTSP5 generated a different /etc/hosts file.

But if it's a problem, of course let's examine it. Here is what a local Ubuntu puts in /etc/hosts:

```shell
127.0.0.1	localhost
127.0.1.1	focal-mate

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Here is what a local Debian puts in /etc/hosts:

```shell
127.0.0.1	localhost
127.0.1.1	buster-gnome

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Here is what a local Fedora 30 puts in /etc/hosts:

```shell
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

So if Fedora is more correct than Debian and Ubuntu, we can talk about that. We cannot put the boot IP there though by default as it might even be dynamic, e.g. in the AoE case, and I see no distribution doing that anyway.
Removing the entry completely make `getent hosts buster-gnome` reply with an IPv6 IP, while I don't even have IPv6 enabled networking, so I'm not sure how much it will help. Also I don't know what will happen with distributions that don't use systemd-resolved; they will probably not resolve it at all then.

**Comment by kvaps** [comment]
> LTSP tries to imitate what local installations do. Debian and Ubuntu put 127.0.0.1 hostname there, so we've been doing the same thing in LTSP5 for 10+ years now.

I know, this problem persists on all debian and ubuntu based installations. (except cloud-images)
But there is good reason for doing this, because during the local installation you might don't even know the ip address, it also can be changed during the time.
But some services requires resolvable hostname address even if it will be connected to loopback interface, better to have it locally than nothing.

If you're using your debian/ubuntu not for client pc, but for making some server, you more likely will configure right IP and hostname in `/etc/hosts` file by proper way.

Our case is different. We always know the correct IP-address because it is used for boot over network. And it will always updated in dynamic infrastructure after reboot.
So we don't have to solve problems persist to local installations we can just record the correct IP.

> I don't know why you say that LTSP5 generated a different /etc/hosts file.

No it was pretty same, I was talking that we're correcting this IP every time.

> So if Fedora is more correct than Debian and Ubuntu, we can talk about that.

Yep rhel, centos and fedora is going by different way they usually specify nothing in `/etc/hosts` and they specify FQDN (with dots) in `/etc/hostname`, this is also little incorrect according [hostname.5](http://man7.org/linux/man-pages/man5/hostname.5.html), but this is not breaking hostname resolution.

I just want to say that we have everything need to specify it correctly.

**Comment by alkisg** [comment]
> Why? The boot IP can't be changed after the boot, how nfs-client will handle this?

AoE is ATA over Ethernet. It's using Ethernet packets instead of IP packets. AoE clients do not need an IP at all to communicate with the server. They're not using NFS.

> If hostname is not specified in hosts it will query dns every time.

Right, most LTSP users don't have their hostnames in DNS. So DNS will reply with host unknown.

In any case, the idea is to stick to the defaults provided by the distributions, unless they're bugs, in which case we should file bug reports against them, and temporarily work around those bugs in LTSP. E.g. what might seem to solve one problem, might cause 10 different problems for other use cases.
