### ISSUE TITLE
Consider remove sshfs from dependicies

### ISSUE THREAD

**Issue by kvaps** [ltsp/ltsp#98]
`ltsp` package is depends on `sshfs`, which is might be installed only after activation `universe` repository (for the bionic)

```bash
# apt-get install ltsp linux-generic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ltsp : Depends: sshfs but it is not installable
        Recommends: man-db but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Users might use nfs for sharing home, or local users instead, we don't need hard dependency for `sshfs`, consider to move it to recommends?

**Comment by alkisg** [comment]
LTSP will be in universe too.
SSHFS adds 50 KB over SSH.
One of these two is usually needed for authentication.
Dunno, 50 KB don't sound like a big deal... but if it's really a problem, sure we can do that and depend on ssh instead.

**Comment by kvaps** [comment]
50KB is not problem for me, I just came up this to discussion, because I'm not using sshfs.

**Comment by alkisg** [comment]
Thanks, fix committed in https://github.com/ltsp/ltsp/commit/b1f0a05e2c290d7e727098a016771707a2caff3b.
