### ISSUE TITLE
sshfs option 'nonempty' breaks login on Debian client

### ISSUE THREAD

**Issue by schweer-guest** [ltsp/ltsp#99]
As of fuse3, the 'nonempty' fuse option is gone (it's now the default behaviour).
Debian testing ships sshfs 3.6 linked against libfuse3-3, see:
https://packages.debian.org/bullseye/sshfs
Keeping the option, spits out "unknown option(s): `-o nonempty'" when trying to log in.

This change allows one to login.:

```
diff a/pamltsp b/pamltsp 
170,172c170,171
<         # nonempty: in case of .bash_history or local home
<         if "${_SELF%/*}/ssh-askpass" |
<             sshfs -o password_stdin,allow_other,default_permissions,nonempty \
---
>          if "${_SELF%/*}/ssh-askpass" |
>             sshfs -o password_stdin,allow_other,default_permissions \
```

**Comment by alkisg** [comment]
Thank you schweer-guest,

since we do want to support previous versions along with the next ones, I'll prepare something that will involve a version check.

**Comment by alkisg** [comment]
@schweer-guest, could you please send the output of this command?

```shell
sshfs -V
fusermount -V
```

**Comment by alkisg** [comment]
Thanks, fix committed in https://github.com/ltsp/ltsp/commit/29b06648d2c99659d65e0a0e5acef293196cf5e8.

**Comment by alkisg** [comment]
Sorry, is_command isn't available in pamltsp, so the previous fix wasn't appropriate, this one should do the trick:

c48e9fccff5a3e0dd83a622cab5e909b7f34ef3d
